"""Tests for learning & evolution optimization modules (31-15)."""

from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import pytest

from dan.engine.correction_memory import (
    CorrectionRecord,
    CorrectionSignal,
    CorrectionStore,
    detect_correction,
    route_correction,
)
from dan.engine.adaptation_registry import (
    AdaptationCandidate,
    AdaptationRegistry,
)
from dan.engine.planning_calibration import (
    DurationEstimator,
    FailureHotspotPredictor,
    ModelPreference,
)
from dan.engine.learning_tiers import (
    JsonFileBackend,
    LearningHealthCounters,
    SqliteBackend,
    is_feature_enabled,
    resolve_learning_tier,
    resolve_memory_backend,
)


# ===================================================================
# Correction Detection
# ===================================================================


class TestDetectCorrection:
    """Test the heuristic correction detector."""

    def test_negation_strong(self) -> None:
        sig = detect_correction("No, don't do that", "Here is your report.")
        assert sig is not None
        assert sig.correction_type == "negation"
        assert sig.confidence == 0.9

    def test_negation_moderate(self) -> None:
        sig = detect_correction("Not that, something else", "Here is option A.")
        assert sig is not None
        assert sig.correction_type == "negation"
        assert sig.confidence >= 0.7

    def test_override_strong(self) -> None:
        sig = detect_correction("Use Stata instead of Python", "I'll use Python.")
        assert sig is not None
        assert sig.correction_type == "override"
        assert sig.confidence == 0.9

    def test_override_moderate(self) -> None:
        sig = detect_correction("Instead of that approach, try this", "Option A.")
        assert sig is not None
        assert sig.correction_type == "override"
        assert sig.confidence >= 0.7

    def test_style_strong(self) -> None:
        sig = detect_correction("Too long, keep it short", "A very long response...")
        assert sig is not None
        assert sig.correction_type == "style"
        assert sig.confidence == 0.9

    def test_style_moderate(self) -> None:
        sig = detect_correction("Make it shorter", "Here is a detailed analysis...")
        assert sig is not None
        assert sig.correction_type == "style"
        assert sig.confidence >= 0.7

    def test_style_summarize_first(self) -> None:
        sig = detect_correction("Summarize first before the details", "Long report...")
        assert sig is not None
        assert sig.correction_type == "style"
        assert sig.confidence == 0.9

    def test_redo_strong(self) -> None:
        sig = detect_correction("Try again with more detail", "Brief answer.")
        assert sig is not None
        assert sig.correction_type == "redo"
        assert sig.confidence == 0.9

    def test_redo_moderate(self) -> None:
        sig = detect_correction("One more time please", "First attempt.")
        assert sig is not None
        assert sig.correction_type == "redo"
        assert sig.confidence >= 0.7

    def test_preference_strong(self) -> None:
        sig = detect_correction("I prefer Stata for econometrics", "I'll use R.")
        assert sig is not None
        assert sig.correction_type == "preference"
        assert sig.confidence == 0.9
        assert sig.extracted_preference is not None
        assert "Stata" in sig.extracted_preference

    def test_preference_always_use(self) -> None:
        sig = detect_correction("Always use APA format", "I used MLA format.")
        assert sig is not None
        assert sig.correction_type == "preference"
        assert sig.extracted_preference is not None
        assert "APA" in sig.extracted_preference

    def test_preference_never_use(self) -> None:
        sig = detect_correction("Never use GPT-3.5 for final output", "Generated by GPT-3.5.")
        assert sig is not None
        assert sig.correction_type == "preference"
        assert sig.extracted_preference is not None

    def test_no_correction(self) -> None:
        sig = detect_correction("Thanks, that looks great!", "Here is your report.")
        assert sig is None

    def test_empty_messages(self) -> None:
        assert detect_correction("", "something") is None
        assert detect_correction("something", "") is None

    def test_weak_signal(self) -> None:
        sig = detect_correction("No", "Here is something.")
        assert sig is not None
        assert sig.confidence == 0.5

    def test_principle_extraction_style(self) -> None:
        sig = detect_correction("Summarize first before showing data", "Raw data dump.")
        assert sig is not None
        assert sig.extracted_principle is not None
        assert "summarize first" in sig.extracted_principle.lower()

    def test_principle_extraction_override(self) -> None:
        sig = detect_correction("Use Stata instead of R", "I'll use R.")
        assert sig is not None
        assert sig.extracted_principle is not None

    def test_original_output_truncated(self) -> None:
        long_output = "x" * 1000
        sig = detect_correction("No, don't do that", long_output)
        assert sig is not None
        assert len(sig.original_output) == 500


# ===================================================================
# Confidence Scoring
# ===================================================================


class TestConfidenceScoring:
    def test_strong_patterns_score_09(self) -> None:
        for msg in [
            "No, don't do that",
            "Use Python instead of R",
            "Too verbose, keep it short",
            "Try again please",
            "I prefer JSON output",
        ]:
            sig = detect_correction(msg, "Previous output.")
            assert sig is not None
            assert sig.confidence == 0.9, f"Expected 0.9 for: {msg}"

    def test_moderate_patterns_score_07(self) -> None:
        for msg in [
            "Not that approach",
            "Instead of that method",
            "Make it shorter",
            "One more time",
            "I'd rather have CSV",
        ]:
            sig = detect_correction(msg, "Previous output.")
            assert sig is not None
            assert sig.confidence >= 0.7, f"Expected >=0.7 for: {msg}"

    def test_weak_patterns_score_05(self) -> None:
        sig = detect_correction("Actually, let me think", "Previous output.")
        assert sig is not None
        assert sig.confidence == 0.5


# ===================================================================
# Correction Routing
# ===================================================================


class TestRouteCorrection:
    def test_preference_route(self) -> None:
        signal = CorrectionSignal(
            correction_type="preference",
            confidence=0.9,
            extracted_preference="always use Stata",
        )
        actions = route_correction(signal)
        types = [a["type"] for a in actions]
        assert "preference" in types
        assert "negative_evidence" in types

    def test_principle_route(self) -> None:
        signal = CorrectionSignal(
            correction_type="style",
            confidence=0.9,
            extracted_principle="summarize first",
        )
        actions = route_correction(signal)
        types = [a["type"] for a in actions]
        assert "principle" in types
        assert "negative_evidence" in types

    def test_negation_route(self) -> None:
        signal = CorrectionSignal(
            correction_type="negation",
            confidence=0.9,
        )
        actions = route_correction(signal)
        assert len(actions) == 1
        assert actions[0]["type"] == "negative_evidence"
        assert actions[0]["decrement"] == 0.1

    def test_redo_route(self) -> None:
        signal = CorrectionSignal(correction_type="redo", confidence=0.9)
        actions = route_correction(signal)
        assert len(actions) == 1
        assert actions[0]["type"] == "negative_evidence"

    def test_override_with_principle(self) -> None:
        signal = CorrectionSignal(
            correction_type="override",
            confidence=0.9,
            extracted_principle="switch to Stata",
        )
        actions = route_correction(signal)
        types = [a["type"] for a in actions]
        assert "principle" in types
        assert "negative_evidence" in types

    def test_weak_signal_below_threshold_produces_no_actions(self) -> None:
        signal = CorrectionSignal(
            correction_type="negation",
            confidence=0.5,
        )
        assert route_correction(signal) == []


# ===================================================================
# CorrectionStore
# ===================================================================


class TestCorrectionStore:
    def test_add_and_count(self) -> None:
        store = CorrectionStore()
        assert store.count() == 0
        rec = CorrectionRecord(
            signal=CorrectionSignal(correction_type="negation", confidence=0.9),
            actions=[{"type": "negative_evidence", "scope": "negation", "decrement": 0.1}],
        )
        store.add(rec)
        assert store.count() == 1

    def test_list_recent(self) -> None:
        store = CorrectionStore()
        for i in range(30):
            store.add(CorrectionRecord(
                signal=CorrectionSignal(correction_type="negation", confidence=0.5),
            ))
        recent = store.list_recent(20)
        assert len(recent) == 20

    def test_list_recent_fewer(self) -> None:
        store = CorrectionStore()
        store.add(CorrectionRecord(
            signal=CorrectionSignal(correction_type="redo", confidence=0.9),
        ))
        recent = store.list_recent(20)
        assert len(recent) == 1


# ===================================================================
# Adaptation Registry
# ===================================================================


class TestAdaptationRegistry:
    def _make_candidate(self, **kwargs: object) -> AdaptationCandidate:
        defaults = dict(source="prompt_opt", confidence=0.8, sample_size=10)
        defaults.update(kwargs)
        return AdaptationCandidate(**defaults)  # type: ignore[arg-type]

    def test_add_and_list(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        assert reg.count() == 1
        assert len(reg.list_pending()) == 1
        assert len(reg.list_applied()) == 0

    def test_approve(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.approve(c.id)
        assert reg.get(c.id) is not None
        assert reg.get(c.id).status == "applied"
        assert reg.get(c.id).applied_at is not None
        assert len(reg.list_pending()) == 0
        assert len(reg.list_applied()) == 1

    def test_approve_not_found(self) -> None:
        reg = AdaptationRegistry()
        with pytest.raises(KeyError):
            reg.approve("nonexistent")

    def test_approve_wrong_state(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.approve(c.id)
        with pytest.raises(ValueError, match="Cannot approve"):
            reg.approve(c.id)

    def test_reject(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.reject(c.id)
        assert reg.get(c.id).status == "rejected"

    def test_reject_not_found(self) -> None:
        reg = AdaptationRegistry()
        with pytest.raises(KeyError):
            reg.reject("nonexistent")

    def test_reject_wrong_state(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.reject(c.id)
        with pytest.raises(ValueError, match="Cannot reject"):
            reg.reject(c.id)

    def test_rollback(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.approve(c.id)
        reg.rollback(c.id, "quality dropped")
        assert reg.get(c.id).status == "rolled_back"
        assert reg.get(c.id).last_outcome == "quality dropped"

    def test_rollback_not_applied(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        with pytest.raises(ValueError, match="Cannot rollback"):
            reg.rollback(c.id, "reason")

    def test_regression_detected(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.approve(c.id)
        detected = reg.check_regression(c.id, recent_quality=0.6, baseline_quality=0.9)
        assert detected is True
        assert reg.get(c.id).status == "rolled_back"

    def test_no_regression(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.approve(c.id)
        detected = reg.check_regression(c.id, recent_quality=0.85, baseline_quality=0.9)
        assert detected is False
        assert reg.get(c.id).status == "applied"

    def test_regression_zero_baseline(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.approve(c.id)
        assert reg.check_regression(c.id, recent_quality=0.5, baseline_quality=0.0) is False

    def test_regression_custom_threshold(self) -> None:
        reg = AdaptationRegistry()
        c = self._make_candidate()
        reg.add(c)
        reg.approve(c.id)
        detected = reg.check_regression(
            c.id, recent_quality=0.8, baseline_quality=0.9, threshold=0.05,
        )
        assert detected is True

    def test_regression_not_found(self) -> None:
        reg = AdaptationRegistry()
        with pytest.raises(KeyError):
            reg.check_regression("nope", 0.5, 0.9)


# ===================================================================
# Duration Estimation
# ===================================================================


class TestDurationEstimator:
    def setup_method(self) -> None:
        self.est = DurationEstimator()

    def test_quick_classification(self) -> None:
        median, ci = self.est.estimate("Translate this paragraph to French")
        assert median == 2.0
        assert ci == 1.0

    def test_medium_classification(self) -> None:
        median, ci = self.est.estimate("Process this data set")
        assert median == 15.0

    def test_complex_classification(self) -> None:
        median, ci = self.est.estimate("Write a comprehensive research paper")
        assert median == 30.0
        assert ci == 15.0

    def test_complex_literature_review(self) -> None:
        median, _ = self.est.estimate("Conduct a literature review on supply chain")
        assert median == 30.0

    def test_node_type_hint(self) -> None:
        median, ci = self.est.estimate("Do something", node_type="code_operator")
        assert median == 5.0

    def test_default_medium(self) -> None:
        median, _ = self.est.estimate("Do something generic")
        assert median == 15.0


# ===================================================================
# Failure Hotspot Predictor
# ===================================================================


class TestFailureHotspotPredictor:
    def setup_method(self) -> None:
        self.pred = FailureHotspotPredictor()

    def test_code_operator(self) -> None:
        prob, advice = self.pred.predict("code_operator")
        assert prob == 0.20
        assert "20%" in advice

    def test_tool_operator(self) -> None:
        prob, advice = self.pred.predict("tool_operator")
        assert prob == 0.15

    def test_llm_operator(self) -> None:
        prob, advice = self.pred.predict("llm_operator")
        assert prob == 0.05

    def test_unknown_type(self) -> None:
        prob, advice = self.pred.predict("custom_node")
        assert prob == 0.08
        assert "default" in advice.lower()


# ===================================================================
# Model Preference
# ===================================================================


class TestModelPreference:
    def setup_method(self) -> None:
        self.pref = ModelPreference()

    def test_code_node(self) -> None:
        result = self.pref.recommend("code_operator")
        assert result == "reasoning"

    def test_tool_node(self) -> None:
        result = self.pref.recommend("tool_operator")
        assert result == "micro"

    def test_llm_node(self) -> None:
        result = self.pref.recommend("llm_operator")
        assert result == "routine"

    def test_task_pattern_override(self) -> None:
        result = self.pref.recommend("llm_operator", task_pattern="code_generation task")
        assert result == "reasoning"

    def test_research_pattern(self) -> None:
        result = self.pref.recommend("llm_operator", task_pattern="research project")
        assert result == "critical"

    def test_unknown_node(self) -> None:
        result = self.pref.recommend("unknown_type")
        assert result is None

    def test_unknown_with_pattern(self) -> None:
        result = self.pref.recommend("unknown_type", task_pattern="simple query")
        assert result == "micro"


# ===================================================================
# Learning Tier Resolution
# ===================================================================


class TestLearningTier:
    def test_default_tier_zero(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.delenv("DAN_LEARNING_TIER", raising=False)
        monkeypatch.delenv("DAN_LEARNING_MODE", raising=False)
        assert resolve_learning_tier() == 0

    def test_explicit_tier(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("DAN_LEARNING_TIER", "2")
        assert resolve_learning_tier() == 2

    def test_tier_clamped_high(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("DAN_LEARNING_TIER", "5")
        assert resolve_learning_tier() == 2

    def test_tier_clamped_low(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("DAN_LEARNING_TIER", "-1")
        assert resolve_learning_tier() == 0

    def test_backward_compat_learning_mode(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.delenv("DAN_LEARNING_TIER", raising=False)
        monkeypatch.setenv("DAN_LEARNING_MODE", "1")
        assert resolve_learning_tier() == 1

    def test_tier_overrides_mode(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("DAN_LEARNING_TIER", "0")
        monkeypatch.setenv("DAN_LEARNING_MODE", "1")
        assert resolve_learning_tier() == 0

    def test_invalid_tier_falls_back(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("DAN_LEARNING_TIER", "abc")
        monkeypatch.delenv("DAN_LEARNING_MODE", raising=False)
        assert resolve_learning_tier() == 0


class TestFeatureEnabled:
    def test_tier_0_features(self, monkeypatch: pytest.MonkeyPatch) -> None:
        for key in ("DAN_PROMPT_OPTIMIZATION", "DAN_MODEL_LEARNING", "DAN_TOPOLOGY_LEARNING", "DAN_SKILL_LEARNING", "DAN_MEMORY_EXTRACTION"):
            monkeypatch.delenv(key, raising=False)
        assert is_feature_enabled("memory", tier=0)
        assert is_feature_enabled("post_run_learning", tier=0)
        assert is_feature_enabled("reuse_scoring", tier=0)
        assert not is_feature_enabled("topology_suggestions", tier=0)
        assert not is_feature_enabled("auto_adaptation", tier=0)

    def test_tier_1_includes_0(self, monkeypatch: pytest.MonkeyPatch) -> None:
        for key in ("DAN_PROMPT_OPTIMIZATION", "DAN_MODEL_LEARNING", "DAN_TOPOLOGY_LEARNING", "DAN_SKILL_LEARNING", "DAN_MEMORY_EXTRACTION"):
            monkeypatch.delenv(key, raising=False)
        assert is_feature_enabled("memory", tier=1)
        assert is_feature_enabled("topology_suggestions", tier=1)
        assert is_feature_enabled("model_recommendations", tier=1)
        assert not is_feature_enabled("auto_adaptation", tier=1)

    def test_tier_2_includes_all(self, monkeypatch: pytest.MonkeyPatch) -> None:
        for key in ("DAN_PROMPT_OPTIMIZATION", "DAN_MODEL_LEARNING", "DAN_TOPOLOGY_LEARNING", "DAN_SKILL_LEARNING", "DAN_MEMORY_EXTRACTION"):
            monkeypatch.delenv(key, raising=False)
        assert is_feature_enabled("memory", tier=2)
        assert is_feature_enabled("topology_suggestions", tier=2)
        assert is_feature_enabled("auto_adaptation", tier=2)
        assert is_feature_enabled("ab_prompt_promotion", tier=2)

    def test_unknown_feature(self) -> None:
        assert not is_feature_enabled("nonexistent_feature", tier=2)


# ===================================================================
# Health Counters
# ===================================================================


class TestHealthCounters:
    def test_record_success(self) -> None:
        hc = LearningHealthCounters()
        hc.record("memory_extraction", "success")
        summary = hc.get_summary()
        assert summary["memory_extraction"]["attempted"] == 1
        assert summary["memory_extraction"]["succeeded"] == 1

    def test_record_skip(self) -> None:
        hc = LearningHealthCounters()
        hc.record("run_learning", "skip")
        summary = hc.get_summary()
        assert summary["run_learning"]["skipped"] == 1
        assert summary["run_learning"]["attempted"] == 1

    def test_record_fail(self) -> None:
        hc = LearningHealthCounters()
        hc.record("prompt_tracking", "fail")
        summary = hc.get_summary()
        assert summary["prompt_tracking"]["failed"] == 1

    def test_multiple_records(self) -> None:
        hc = LearningHealthCounters()
        for _ in range(5):
            hc.record("model_tracking", "success")
        hc.record("model_tracking", "fail")
        summary = hc.get_summary()
        assert summary["model_tracking"]["attempted"] == 6
        assert summary["model_tracking"]["succeeded"] == 5
        assert summary["model_tracking"]["failed"] == 1

    def test_unknown_path_created(self) -> None:
        hc = LearningHealthCounters()
        hc.record("custom_path", "success")
        summary = hc.get_summary()
        assert "custom_path" in summary
        assert summary["custom_path"]["succeeded"] == 1

    def test_format_status(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setenv("DAN_LEARNING_TIER", "1")
        hc = LearningHealthCounters()
        hc.record("memory_extraction", "success")
        hc.record("memory_extraction", "success")
        hc.record("memory_extraction", "fail")
        status = hc.format_status()
        assert "Learning tier: 1" in status
        assert "memory_extraction" in status
        assert "3 attempted" in status
        assert "2 ok" in status
        assert "1 failed" in status

    def test_format_status_no_events(self) -> None:
        hc = LearningHealthCounters()
        status = hc.format_status()
        assert "no events" in status

    def test_all_default_paths_present(self) -> None:
        hc = LearningHealthCounters()
        summary = hc.get_summary()
        for path in [
            "memory_extraction", "run_learning", "prompt_tracking",
            "model_tracking", "topology_tracking", "skill_tracking",
        ]:
            assert path in summary


# ===================================================================
# Memory Backend: JsonFileBackend
# ===================================================================


class TestJsonFileBackend:
    def test_load_empty(self, tmp_path: Path) -> None:
        backend = JsonFileBackend(tmp_path / "mem.json")
        assert backend.load() == {}

    def test_save_and_load(self, tmp_path: Path) -> None:
        backend = JsonFileBackend(tmp_path / "mem.json")
        backend.save({"item1": {"content": "hello", "memory_type": "fact"}})
        loaded = backend.load()
        assert "item1" in loaded
        assert loaded["item1"]["content"] == "hello"

    def test_upsert(self, tmp_path: Path) -> None:
        backend = JsonFileBackend(tmp_path / "mem.json")
        backend.upsert("id1", {"content": "first"})
        backend.upsert("id2", {"content": "second"})
        loaded = backend.load()
        assert len(loaded) == 2
        backend.upsert("id1", {"content": "updated"})
        loaded = backend.load()
        assert loaded["id1"]["content"] == "updated"

    def test_delete(self, tmp_path: Path) -> None:
        backend = JsonFileBackend(tmp_path / "mem.json")
        backend.upsert("id1", {"content": "hello"})
        backend.delete("id1")
        assert backend.load() == {}

    def test_delete_nonexistent(self, tmp_path: Path) -> None:
        backend = JsonFileBackend(tmp_path / "mem.json")
        backend.delete("nonexistent")

    def test_query_by_type(self, tmp_path: Path) -> None:
        backend = JsonFileBackend(tmp_path / "mem.json")
        backend.save({
            "a": {"memory_type": "fact", "content": "x"},
            "b": {"memory_type": "preference", "content": "y"},
            "c": {"memory_type": "fact", "content": "z"},
        })
        results = backend.query(memory_type="fact")
        assert len(results) == 2

    def test_query_no_match(self, tmp_path: Path) -> None:
        backend = JsonFileBackend(tmp_path / "mem.json")
        backend.save({"a": {"memory_type": "fact"}})
        results = backend.query(memory_type="principle")
        assert len(results) == 0

    def test_corrupted_file(self, tmp_path: Path) -> None:
        path = tmp_path / "mem.json"
        path.write_text("not json", encoding="utf-8")
        backend = JsonFileBackend(path)
        assert backend.load() == {}


# ===================================================================
# Memory Backend: SqliteBackend
# ===================================================================


class TestSqliteBackend:
    def test_load_empty(self, tmp_path: Path) -> None:
        backend = SqliteBackend(tmp_path / "mem.db")
        try:
            assert backend.load() == {}
        finally:
            backend.close()

    def test_save_and_load(self, tmp_path: Path) -> None:
        backend = SqliteBackend(tmp_path / "mem.db")
        try:
            backend.save({"item1": {"content": "hello", "memory_type": "fact"}})
            loaded = backend.load()
            assert "item1" in loaded
            assert loaded["item1"]["content"] == "hello"
        finally:
            backend.close()

    def test_upsert(self, tmp_path: Path) -> None:
        backend = SqliteBackend(tmp_path / "mem.db")
        try:
            backend.upsert("id1", {"content": "first", "memory_type": "fact"})
            backend.upsert("id2", {"content": "second", "memory_type": "pref"})
            loaded = backend.load()
            assert len(loaded) == 2
            backend.upsert("id1", {"content": "updated", "memory_type": "fact"})
            loaded = backend.load()
            assert loaded["id1"]["content"] == "updated"
        finally:
            backend.close()

    def test_delete(self, tmp_path: Path) -> None:
        backend = SqliteBackend(tmp_path / "mem.db")
        try:
            backend.upsert("id1", {"content": "hello"})
            backend.delete("id1")
            assert backend.load() == {}
        finally:
            backend.close()

    def test_query_by_type(self, tmp_path: Path) -> None:
        backend = SqliteBackend(tmp_path / "mem.db")
        try:
            backend.save({
                "a": {"memory_type": "fact", "content": "x"},
                "b": {"memory_type": "preference", "content": "y"},
                "c": {"memory_type": "fact", "content": "z"},
            })
            results = backend.query(memory_type="fact")
            assert len(results) == 2
        finally:
            backend.close()

    def test_query_no_match(self, tmp_path: Path) -> None:
        backend = SqliteBackend(tmp_path / "mem.db")
        try:
            backend.save({"a": {"memory_type": "fact"}})
            results = backend.query(memory_type="principle")
            assert len(results) == 0
        finally:
            backend.close()

    def test_query_rejects_invalid_json_key(self, tmp_path: Path) -> None:
        backend = SqliteBackend(tmp_path / "mem.db")
        try:
            backend.save({"a": {"memory_type": "fact", "project_id": "p1"}})
            with pytest.raises(ValueError, match="Invalid filter key"):
                backend.query(**{"project-id": "p1"})
        finally:
            backend.close()


# ===================================================================
# resolve_memory_backend
# ===================================================================


class TestResolveMemoryBackend:
    def test_default_json(self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
        monkeypatch.delenv("DAN_MEMORY_BACKEND", raising=False)
        backend = resolve_memory_backend(tmp_path)
        assert isinstance(backend, JsonFileBackend)

    def test_sqlite(self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
        monkeypatch.setenv("DAN_MEMORY_BACKEND", "sqlite")
        backend = resolve_memory_backend(tmp_path)
        assert isinstance(backend, SqliteBackend)
        backend.close()

    def test_unknown_falls_to_json(self, monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
        monkeypatch.setenv("DAN_MEMORY_BACKEND", "postgres")
        backend = resolve_memory_backend(tmp_path)
        assert isinstance(backend, JsonFileBackend)
