"""Chat manager support package — events, prompts, tokens, graph summary, mutation parsing, helpers."""

from dan.server.chat.events import (
    ChatCodeGeneratedEvent,
    ChatCompleteEvent,
    ChatErrorEvent,
    ChatFileAttachmentEvent,
    ChatGenerationSummaryEvent,
    ChatGraphCreatedEvent,
    ChatGraphQualityEvent,
    ChatIntentExtractedEvent,
    ChatInterruptedEvent,
    ChatMultiPartEvent,
    ChatMutationEvent,
    ChatPollRequestEvent,
    ChatQueuedEvent,
    ChatStreamEvent,
    ChatTokenEvent,
    ChatToolCallResultEvent,
    ChatToolCallStartEvent,
    ChatValidationResultEvent,
    EdgeSummary,
    GraphSummary,
    NodeSummary,
)
from dan.server.chat.graph_summary import (
    build_graph_summary,
    compute_graph_revision,
    serialize_for_prompt,
)
from dan.server.chat.helpers import (
    build_debug_context,
    detect_chat_mode,
    normalize_chat_mode,
    recent_run_failed_for_workflow,
)
from dan.server.chat.mutation_parser import (
    _coerce_strict_edges,
    _normalize_generated_mutation_ops,
    normalize_mutation_ops_for_chat,
)
from dan.server.chat.prompts import (
    BUILD_FROM_INTENT_PROMPT,
    EMPTY_GRAPH_SUMMARY_PLACEHOLDER,
    MUTATION_TOOL_SCHEMA,
    WORKFLOW_TEMPLATES,
    generate_capability_reference,
    invalidate_capability_cache,
)
from dan.server.chat.tokens import (
    MODEL_CONTEXT_WINDOWS,
    compact_history,
    context_pressure_hint,
    estimate_tokens,
)

__all__ = [
    "NodeSummary",
    "EdgeSummary",
    "GraphSummary",
    "ChatTokenEvent",
    "ChatCompleteEvent",
    "ChatErrorEvent",
    "ChatMutationEvent",
    "ChatInterruptedEvent",
    "ChatToolCallStartEvent",
    "ChatToolCallResultEvent",
    "ChatIntentExtractedEvent",
    "ChatCodeGeneratedEvent",
    "ChatValidationResultEvent",
    "ChatGraphCreatedEvent",
    "ChatGraphQualityEvent",
    "ChatQueuedEvent",
    "ChatFileAttachmentEvent",
    "ChatPollRequestEvent",
    "ChatMultiPartEvent",
    "ChatGenerationSummaryEvent",
    "ChatStreamEvent",
    "MUTATION_TOOL_SCHEMA",
    "build_graph_summary",
    "serialize_for_prompt",
    "compute_graph_revision",
    "BUILD_FROM_INTENT_PROMPT",
    "EMPTY_GRAPH_SUMMARY_PLACEHOLDER",
    "WORKFLOW_TEMPLATES",
    "normalize_chat_mode",
    "recent_run_failed_for_workflow",
    "detect_chat_mode",
    "build_debug_context",
    "_coerce_strict_edges",
    "_normalize_generated_mutation_ops",
    "normalize_mutation_ops_for_chat",
    "estimate_tokens",
    "context_pressure_hint",
    "compact_history",
    "MODEL_CONTEXT_WINDOWS",
    "generate_capability_reference",
    "invalidate_capability_cache",
]
