"""Compile markdown workflow specs into ``dan_graph_v1`` graphs."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from dan.loader.diagnostics import CompileResult, Diagnostic, format_diagnostics
from dan.loader.flow_parser import FlowParseError, parse_flow_line
from dan.loader.models import (
    AgentSpec,
    ChainStatement,
    ContextSpec,
    EachStatement,
    FlowStatement,
    IfStatement,
    LoopStatement,
    PortSpec,
    SourceLocation,
)
from dan.loader.parser import ParseError, parse_agent_file, parse_workflow_file
from dan.loader.types import (
    SchemaLoadError,
    infer_port_schema,
    infer_schema_from_name,
    load_linked_schema,
)
from dan.models.context import SharedContextDeclaration
from dan.models.control_flow import (
    CompositeNode,
    ForEachNode,
    GateNode,
    HumanInTheLoopNode,
    InputNode,
    InputVariable,
    RouterNode,
)
from dan.models.edges import DataEdge
from dan.models.graph import Graph, GraphMetadata
from dan.models.nodes import CodeOperator, LLMOperator, NodeBase, RetryPolicy, ToolOperator
from dan.models.ports import InputPort, OutputPort

DEFAULT_OUTPUT_PORTS: dict[str, str] = {
    "llm_operator": "text",
    "tool_operator": "result",
    "code_operator": "result",
    "gate": "true",
    "for_each": "results",
    "router": "route",
    "human_in_the_loop": "response",
    "composite": "result",
    "input": "output",
}
DEFAULT_INPUT_PORT = "input"

_VALIDATION_WARNING_PATTERNS = (
    "schema safety bypassed",
    "untyped data edge",
    "deprecated",
)


def compile(path: str | Path) -> Graph:
    """Compile workflow markdown and raise on errors."""
    result = compile_workflow(path)
    if result.graph is None:
        raise ValueError(f"Workflow compilation failed:\n{format_diagnostics(result.diagnostics)}")
    return result.graph


def compile_workflow(workflow_path: str | Path) -> CompileResult:
    """Compile a workflow markdown file into a Graph with diagnostics."""
    workflow_file = Path(workflow_path)
    diagnostics: list[Diagnostic] = []

    try:
        workflow_spec = parse_workflow_file(workflow_file)
    except (ParseError, FlowParseError, FileNotFoundError, OSError) as exc:
        _emit_error(
            diagnostics,
            f"Failed to parse workflow file: {exc}",
            source_file=workflow_file,
        )
        return CompileResult(graph=None, diagnostics=diagnostics)

    for msg, src in workflow_spec.parse_warnings:
        _emit_warning(diagnostics, msg, source=src)

    workflow_dir = workflow_file.parent
    agent_specs: dict[str, AgentSpec] = {}
    for agent_id, rel_path in workflow_spec.agents.items():
        agent_path = (workflow_dir / rel_path).resolve()
        if not agent_path.exists():
            _emit_error(
                diagnostics,
                f"Agent file not found for '{agent_id}': {agent_path}",
                source_file=workflow_file,
            )
            continue
        try:
            spec = parse_agent_file(agent_path)
            spec.name = agent_id
            agent_specs[agent_id] = spec
        except (ParseError, FileNotFoundError, OSError) as exc:
            _emit_error(
                diagnostics,
                f"Failed to parse agent file '{agent_id}': {exc}",
                source_file=agent_path,
            )

    nodes_by_id: dict[str, NodeBase] = {}
    sub_graphs: dict[str, Graph] = {}
    for name, spec in agent_specs.items():
        if name in nodes_by_id:
            _emit_error(
                diagnostics,
                f"Duplicate node id '{name}' in workflow agents",
                source=spec.source,
            )
            continue
        node, nested_sub_graphs = _compile_agent(name, spec, diagnostics)
        if node is None:
            continue
        nodes_by_id[name] = node
        for key, sub_graph in nested_sub_graphs.items():
            if key in sub_graphs:
                _emit_error(
                    diagnostics,
                    f"Duplicate sub-graph key '{key}' generated during agent compilation",
                    source=spec.source,
                )
            else:
                sub_graphs[key] = sub_graph

    edge_counter = [0]
    flow_edges, flow_nodes, flow_subgraphs = _compile_flow(
        workflow_spec.flow_statements,
        nodes_by_id,
        agent_specs,
        diagnostics,
        edge_counter,
    )
    for node in flow_nodes:
        if node.id in nodes_by_id:
            _emit_error(
                diagnostics,
                f"Duplicate node id '{node.id}' generated by flow compilation",
                source_file=workflow_file,
            )
            continue
        nodes_by_id[node.id] = node
    for key, sub_graph in flow_subgraphs.items():
        if key in sub_graphs:
            _emit_error(
                diagnostics,
                f"Duplicate sub-graph key '{key}' generated by flow compilation",
                source_file=workflow_file,
            )
            continue
        sub_graphs[key] = sub_graph

    _auto_wire(list(nodes_by_id.values()), flow_edges, diagnostics)
    input_node = _create_input_node(
        list(nodes_by_id.values()),
        flow_edges,
        diagnostics,
        edge_counter,
    )
    if input_node is not None:
        nodes_by_id[input_node.id] = input_node

    shared_context = _compile_context(workflow_spec.context_declarations, diagnostics)
    nodes = list(nodes_by_id.values())
    entry_points = _find_entry_points(nodes, flow_edges)
    if input_node is not None:
        entry_points = [input_node.id]
    exit_points = _find_exit_points(nodes, flow_edges)

    graph = Graph(
        metadata=GraphMetadata(
            name=workflow_spec.name,
            description=workflow_spec.description,
            tags=list(workflow_spec.tags),
        ),
        nodes=nodes,
        edges=flow_edges,
        sub_graphs=sub_graphs,
        entry_points=entry_points,
        exit_points=exit_points,
        shared_context=shared_context,
    )

    try:
        from dan.validation.graph import validate_graph

        validation_messages = validate_graph(graph)
        for msg in validation_messages:
            level = "warning" if _is_validation_warning(msg) else "error"
            diagnostics.append(
                Diagnostic(
                    level=level,
                    message=msg,
                    source_file=workflow_file,
                )
            )
    except Exception as exc:
        _emit_error(
            diagnostics,
            f"Graph validation failed unexpectedly: {exc}",
            source_file=workflow_file,
        )

    if any(d.level == "error" for d in diagnostics):
        return CompileResult(graph=None, diagnostics=diagnostics)
    return CompileResult(graph=graph, diagnostics=diagnostics)


def _compile_agent(
    name: str,
    spec: AgentSpec,
    diagnostics: list[Diagnostic],
) -> tuple[NodeBase | None, dict[str, Graph]]:
    input_ports = _build_input_ports(spec, diagnostics)
    output_ports = _build_output_ports(spec, diagnostics)
    metadata = _source_metadata(spec.source, spec.file_path)
    nested_sub_graphs: dict[str, Graph] = {}
    node: NodeBase | None = None

    if spec.agent_type == "llm":
        node = LLMOperator(
            id=name,
            name=name,
            model=spec.model,
            prompt_template=spec.prompt_body,
            system_prompt=spec.system_prompt,
            temperature=spec.temperature,
            max_tokens=spec.max_tokens,
            output_json_schema=spec.output_schema,
            input_ports=input_ports,
            output_ports=output_ports,
            metadata=metadata,
        )
    elif spec.agent_type == "tool":
        node = ToolOperator(
            id=name,
            name=name,
            tool_id=spec.tool_id,
            tool_config=dict(spec.tool_config),
            input_ports=input_ports,
            output_ports=output_ports,
            metadata=metadata,
        )
    elif spec.agent_type == "code":
        node = CodeOperator(
            id=name,
            name=name,
            code=spec.prompt_body,
            language=spec.language or "python",
            input_ports=input_ports,
            output_ports=output_ports,
            metadata=metadata,
        )
    elif spec.agent_type == "human":
        node = HumanInTheLoopNode(
            id=name,
            name=name,
            prompt=spec.prompt_body,
            timeout_seconds=spec.timeout_seconds,
            default_action=spec.default_action,
            input_ports=input_ports,
            output_ports=output_ports,
            metadata=metadata,
        )
    elif spec.agent_type == "router":
        node = RouterNode(
            id=name,
            name=name,
            model=spec.model,
            route_descriptions=dict(spec.route_descriptions),
            input_ports=input_ports,
            output_ports=output_ports,
            metadata=metadata,
        )
    elif spec.agent_type == "composite":
        sub_key = f"{name}__body"
        sub_graph = _compile_composite_subgraph(name, spec, diagnostics)
        nested_sub_graphs[sub_key] = sub_graph
        node = CompositeNode(
            id=name,
            name=name,
            body_graph=sub_key,
            input_ports=input_ports,
            output_ports=output_ports,
            metadata=metadata,
        )
    else:
        _emit_error(
            diagnostics,
            f"Unsupported agent type '{spec.agent_type}' on '{name}'",
            source=spec.source,
        )
        return None, nested_sub_graphs

    if spec.retry_policy:
        try:
            node.retry_policy = RetryPolicy(**spec.retry_policy)
        except Exception as exc:
            _emit_error(
                diagnostics,
                f"Invalid retry_policy on '{name}': {exc}",
                source=spec.source,
            )

    return node, nested_sub_graphs


def _agents_used_outside_each_body(statements: list[FlowStatement]) -> set[str]:
    """Agents that appear in chains, if/else, or loop (not only as each body)."""
    used: set[str] = set()
    for stmt in statements:
        if isinstance(stmt, ChainStatement):
            used.update(stmt.agents)
        elif isinstance(stmt, EachStatement):
            used.add(stmt.source_agent)  # body lives in subgraph only
        elif isinstance(stmt, IfStatement):
            used.update((stmt.then_agent, stmt.else_agent))
        elif isinstance(stmt, LoopStatement):
            used.add(stmt.body_agent)
    return used


def _compile_flow(
    statements: list[FlowStatement],
    nodes_by_id: dict[str, NodeBase],
    agent_specs: dict[str, AgentSpec],
    diagnostics: list[Diagnostic],
    edge_counter: list[int],
) -> tuple[list[DataEdge], list[NodeBase], dict[str, Graph]]:
    edges: list[DataEdge] = []
    generated_nodes: list[NodeBase] = []
    generated_subgraphs: dict[str, Graph] = {}
    generated_ids: set[str] = set()
    generated_subgraph_ids: set[str] = set()
    agents_used_outside_each = _agents_used_outside_each_body(statements)

    for stmt in statements:
        if isinstance(stmt, ChainStatement):
            edges.extend(
                _compile_chain_statement(
                    stmt,
                    nodes_by_id,
                    diagnostics,
                    edge_counter,
                )
            )
            continue

        if isinstance(stmt, EachStatement):
            if stmt.source_agent not in nodes_by_id:
                _emit_error(
                    diagnostics,
                    f"Unknown source agent '{stmt.source_agent}' in each()",
                    source=stmt.source,
                )
                continue
            if stmt.body_agent not in nodes_by_id or stmt.body_agent not in agent_specs:
                _emit_error(
                    diagnostics,
                    f"Unknown body agent '{stmt.body_agent}' in each()",
                    source=stmt.source,
                )
                continue

            foreach_id = _ensure_unique_id(
                f"{stmt.source_agent}_each_{stmt.body_agent}",
                set(nodes_by_id) | generated_ids,
            )
            generated_ids.add(foreach_id)

            body_spec = agent_specs[stmt.body_agent]
            body_node, nested = _compile_agent(stmt.body_agent, body_spec, diagnostics)
            if body_node is None:
                _emit_error(
                    diagnostics,
                    f"Could not compile body agent '{stmt.body_agent}' for each()",
                    source=stmt.source,
                )
                continue

            sub_key = _ensure_unique_id(
                f"{foreach_id}__body",
                set(generated_subgraphs) | generated_subgraph_ids,
            )
            generated_subgraph_ids.add(sub_key)

            body_graph = Graph(
                metadata=GraphMetadata(name=f"{foreach_id}_body"),
                nodes=[body_node],
                edges=[],
                sub_graphs=nested,
                entry_points=[body_node.id],
                exit_points=[body_node.id],
            )
            generated_subgraphs[sub_key] = body_graph

            foreach_node = ForEachNode(
                id=foreach_id,
                name=foreach_id,
                body_graph=sub_key,
                parallelism=max(1, stmt.parallel),
                input_ports=[
                    InputPort(
                        name="items",
                        json_schema={},
                    )
                ],
                output_ports=[
                    OutputPort(
                        name="results",
                        json_schema={},
                    )
                ],
                metadata=_source_metadata(stmt.source),
            )
            generated_nodes.append(foreach_node)

            source_node = nodes_by_id[stmt.source_agent]
            edges.append(
                _make_data_edge(
                    stmt.source_agent,
                    _default_output_port(source_node),
                    foreach_id,
                    "items",
                    edge_counter,
                    stmt.source,
                )
            )
            # Body used only in this each: remove from main graph so we don't create
            # workflow_inputs.item → body (body receives items from ForEach at runtime)
            if stmt.body_agent not in agents_used_outside_each:
                nodes_by_id.pop(stmt.body_agent, None)
            continue

        if isinstance(stmt, LoopStatement):
            if stmt.source_agent not in nodes_by_id:
                _emit_error(
                    diagnostics,
                    f"Unknown source agent '{stmt.source_agent}' in loop()",
                    source=stmt.source,
                )
                continue
            if stmt.body_agent not in nodes_by_id:
                _emit_error(
                    diagnostics,
                    f"Unknown body agent '{stmt.body_agent}' in loop()",
                    source=stmt.source,
                )
                continue

            gate_id = _ensure_unique_id(
                f"{stmt.source_agent}_loop_{stmt.body_agent}",
                set(nodes_by_id) | generated_ids,
            )
            generated_ids.add(gate_id)
            gate_node = GateNode(
                id=gate_id,
                name=gate_id,
                gate_mode="while",
                condition=stmt.condition,
                max_iterations=max(1, stmt.max_iterations),
                input_ports=[InputPort(name=DEFAULT_INPUT_PORT, required=True)],
                metadata=_source_metadata(stmt.source),
            )
            nodes_by_id[gate_id] = gate_node  # add immediately so subsequent flow can reference gate (e.g. gate.done → next)
            # Do not append to generated_nodes — already in nodes_by_id; avoids duplicate-id error

            source_node = nodes_by_id[stmt.source_agent]
            body_node = nodes_by_id[stmt.body_agent]
            body_target_port = _default_input_port(body_node)
            body_source_port = _default_output_port(body_node)

            edges.append(
                _make_data_edge(
                    stmt.source_agent,
                    _default_output_port(source_node),
                    gate_id,
                    DEFAULT_INPUT_PORT,
                    edge_counter,
                    stmt.source,
                )
            )
            edges.append(
                _make_data_edge(
                    gate_id,
                    "continue",
                    stmt.body_agent,
                    body_target_port,
                    edge_counter,
                    stmt.source,
                )
            )
            edges.append(
                _make_data_edge(
                    stmt.body_agent,
                    body_source_port,
                    gate_id,
                    DEFAULT_INPUT_PORT,
                    edge_counter,
                    stmt.source,
                )
            )
            continue

        if isinstance(stmt, IfStatement):
            if stmt.source_agent not in nodes_by_id:
                _emit_error(
                    diagnostics,
                    f"Unknown source agent '{stmt.source_agent}' in if()",
                    source=stmt.source,
                )
                continue
            if stmt.then_agent not in nodes_by_id:
                _emit_error(
                    diagnostics,
                    f"Unknown then agent '{stmt.then_agent}' in if()",
                    source=stmt.source,
                )
                continue
            if stmt.else_agent not in nodes_by_id:
                _emit_error(
                    diagnostics,
                    f"Unknown else agent '{stmt.else_agent}' in if()",
                    source=stmt.source,
                )
                continue

            gate_id = _ensure_unique_id(
                f"{stmt.source_agent}_if_{stmt.then_agent}_{stmt.else_agent}",
                set(nodes_by_id) | generated_ids,
            )
            generated_ids.add(gate_id)
            gate_node = GateNode(
                id=gate_id,
                name=gate_id,
                gate_mode="if_else",
                condition=stmt.condition,
                input_ports=[InputPort(name=DEFAULT_INPUT_PORT, required=True)],
                metadata=_source_metadata(stmt.source),
            )
            generated_nodes.append(gate_node)

            source_node = nodes_by_id[stmt.source_agent]
            then_node = nodes_by_id[stmt.then_agent]
            else_node = nodes_by_id[stmt.else_agent]
            edges.append(
                _make_data_edge(
                    stmt.source_agent,
                    _default_output_port(source_node),
                    gate_id,
                    DEFAULT_INPUT_PORT,
                    edge_counter,
                    stmt.source,
                )
            )
            edges.append(
                _make_data_edge(
                    gate_id,
                    "true",
                    stmt.then_agent,
                    _default_input_port(then_node),
                    edge_counter,
                    stmt.source,
                )
            )
            edges.append(
                _make_data_edge(
                    gate_id,
                    "false",
                    stmt.else_agent,
                    _default_input_port(else_node),
                    edge_counter,
                    stmt.source,
                )
            )
            continue

        _emit_error(
            diagnostics,
            f"Unsupported flow statement '{type(stmt).__name__}'",
            source=getattr(stmt, "source", None),
        )

    return edges, generated_nodes, generated_subgraphs


def _compile_chain_statement(
    stmt: ChainStatement,
    nodes_by_id: dict[str, NodeBase],
    diagnostics: list[Diagnostic],
    edge_counter: list[int],
) -> list[DataEdge]:
    edges: list[DataEdge] = []
    if len(stmt.agents) < 2:
        _emit_error(
            diagnostics,
            "Chain statement requires at least two agents",
            source=stmt.source,
        )
        return edges

    for index in range(len(stmt.agents) - 1):
        source_id = stmt.agents[index]
        target_id = stmt.agents[index + 1]
        if source_id not in nodes_by_id:
            _emit_error(
                diagnostics,
                f"Unknown source agent '{source_id}' in chain",
                source=stmt.source,
            )
            continue
        if target_id not in nodes_by_id:
            _emit_error(
                diagnostics,
                f"Unknown target agent '{target_id}' in chain",
                source=stmt.source,
            )
            continue

        source_node = nodes_by_id[source_id]
        target_node = nodes_by_id[target_id]
        explicit_source_port = None
        explicit_target_port = None
        if index < len(stmt.port_pairs):
            explicit_source_port, explicit_target_port = stmt.port_pairs[index]

        source_port, target_port = _resolve_chain_ports(
            source_node,
            target_node,
            explicit_source_port,
            explicit_target_port,
            diagnostics,
            stmt.source,
        )
        edges.append(
            _make_data_edge(
                source_id,
                source_port,
                target_id,
                target_port,
                edge_counter,
                stmt.source,
            )
        )
    return edges


def _resolve_chain_ports(
    source_node: NodeBase,
    target_node: NodeBase,
    explicit_source_port: str | None,
    explicit_target_port: str | None,
    diagnostics: list[Diagnostic],
    source: SourceLocation | None,
) -> tuple[str, str]:
    source_names = {port.name for port in source_node.output_ports}
    target_names = {port.name for port in target_node.input_ports}

    if explicit_source_port is not None and explicit_target_port is not None:
        if explicit_source_port not in source_names:
            _emit_error(
                diagnostics,
                f"Source node '{source_node.id}' has no output port '{explicit_source_port}'",
                source=source,
            )
        if explicit_target_port not in target_names:
            _emit_error(
                diagnostics,
                f"Target node '{target_node.id}' has no input port '{explicit_target_port}'",
                source=source,
            )
        return explicit_source_port, explicit_target_port

    if explicit_source_port is not None:
        target_port = explicit_source_port if explicit_source_port in target_names else _default_input_port(target_node)
        return explicit_source_port, target_port

    if explicit_target_port is not None:
        source_port = explicit_target_port if explicit_target_port in source_names else _default_output_port(source_node)
        return source_port, explicit_target_port

    matches = sorted(source_names & target_names)
    if len(matches) == 1:
        return matches[0], matches[0]
    if len(matches) > 1:
        _emit_warning(
            diagnostics,
            (
                f"Ambiguous auto-wire for '{source_node.id} -> {target_node.id}': "
                f"multiple shared ports {matches}; using '{matches[0]}'"
            ),
            source=source,
            hint="Use explicit .port syntax to disambiguate",
        )
        return matches[0], matches[0]

    return _default_output_port(source_node), _default_input_port(target_node)


def _auto_wire(
    nodes: list[NodeBase],
    edges: list[DataEdge],
    diagnostics: list[Diagnostic],
) -> None:
    node_map = {node.id: node for node in nodes}
    for edge in edges:
        source_node = node_map.get(edge.source_node_id)
        target_node = node_map.get(edge.target_node_id)
        if source_node is None or target_node is None:
            continue

        source_names = {port.name for port in source_node.output_ports}
        target_names = {port.name for port in target_node.input_ports}
        source_valid = edge.source_port in source_names
        target_valid = edge.target_port in target_names
        if source_valid and target_valid:
            continue

        matches = sorted(source_names & target_names)
        if len(matches) == 1:
            edge.source_port = matches[0]
            edge.target_port = matches[0]
            continue
        if len(matches) > 1:
            edge.source_port = matches[0]
            edge.target_port = matches[0]
            _emit_warning(
                diagnostics,
                (
                    f"Ambiguous auto-wire fallback for '{edge.source_node_id} -> {edge.target_node_id}': "
                    f"using shared port '{matches[0]}'"
                ),
            )
            continue

        if not source_valid:
            edge.source_port = _default_output_port(source_node)
        if not target_valid:
            edge.target_port = _default_input_port(target_node)


def _create_input_node(
    nodes: list[NodeBase],
    edges: list[DataEdge],
    diagnostics: list[Diagnostic],
    edge_counter: list[int],
) -> InputNode | None:
    incoming: dict[str, set[str]] = {}
    for edge in edges:
        incoming.setdefault(edge.target_node_id, set()).add(edge.target_port)

    missing: dict[str, list[tuple[NodeBase, InputPort]]] = {}
    for node in nodes:
        if node.node_type == "input":
            continue
        connected = incoming.get(node.id, set())
        for port in node.input_ports:
            if not port.required:
                continue
            if port.name not in connected:
                missing.setdefault(port.name, []).append((node, port))

    if not missing:
        return None

    variables: list[InputVariable] = []
    output_ports: list[OutputPort] = []
    for variable_name in sorted(missing):
        consumer_ports = [port for _, port in missing[variable_name]]
        var_type = _infer_input_variable_type(consumer_ports)
        port_schema = _infer_input_port_schema(consumer_ports)
        variables.append(InputVariable(name=variable_name, type=var_type))
        output_ports.append(
            OutputPort(
                name=variable_name,
                json_schema=port_schema,
            )
        )

    input_node = InputNode(
        id="workflow_inputs",
        name="Workflow Inputs",
        variables=variables,
        output_ports=output_ports,
        metadata={"generated": True},
    )
    for variable_name, consumers in missing.items():
        for node, port in consumers:
            edges.append(
                _make_data_edge(
                    input_node.id,
                    variable_name,
                    node.id,
                    port.name,
                    edge_counter,
                )
            )

    _emit_warning(
        diagnostics,
        (
            f"Auto-generated InputNode with {len(variables)} variable(s): "
            f"{', '.join(v.name for v in variables)}"
        ),
    )
    return input_node


def _compile_context(
    context_specs: list[ContextSpec],
    diagnostics: list[Diagnostic],
) -> list[SharedContextDeclaration]:
    declarations: list[SharedContextDeclaration] = []
    for spec in context_specs:
        try:
            declarations.append(
                SharedContextDeclaration(
                    key=spec.key,
                    description=spec.description,
                )
            )
        except Exception as exc:
            _emit_error(
                diagnostics,
                f"Invalid context declaration '{spec.key}': {exc}",
                source=spec.source,
            )
    return declarations


def _compile_composite_subgraph(
    parent_name: str,
    spec: AgentSpec,
    diagnostics: list[Diagnostic],
) -> Graph:
    base_dir = spec.file_path.parent if spec.file_path else Path.cwd()
    internal_specs: dict[str, AgentSpec] = {}
    for alias, rel_path in spec.internal_agents.items():
        nested_path = (base_dir / rel_path).resolve()
        if not nested_path.exists():
            _emit_error(
                diagnostics,
                f"Composite '{parent_name}' references missing agent file: {nested_path}",
                source=spec.source,
            )
            continue
        try:
            nested_spec = parse_agent_file(nested_path)
            nested_spec.name = alias
            internal_specs[alias] = nested_spec
        except (ParseError, FileNotFoundError, OSError) as exc:
            _emit_error(
                diagnostics,
                f"Failed to parse composite internal agent '{alias}': {exc}",
                source=spec.source,
            )

    statements: list[FlowStatement] = []
    for index, flow_line in enumerate(spec.internal_flow_lines):
        try:
            flow_source = SourceLocation(
                file=spec.file_path or Path("<unknown>"),
                line=(spec.source.line if spec.source else 0) + index + 1,
            )
            statements.append(parse_flow_line(flow_line, source=flow_source))
        except FlowParseError as exc:
            _emit_error(
                diagnostics,
                f"Failed to parse composite flow line '{flow_line}': {exc}",
                source=spec.source,
            )

    nodes_by_id: dict[str, NodeBase] = {}
    sub_graphs: dict[str, Graph] = {}
    for alias, nested_spec in internal_specs.items():
        node, nested_subgraphs = _compile_agent(alias, nested_spec, diagnostics)
        if node is None:
            continue
        nodes_by_id[alias] = node
        sub_graphs.update(nested_subgraphs)

    edge_counter = [0]
    edges, flow_nodes, flow_subgraphs = _compile_flow(
        statements,
        nodes_by_id,
        internal_specs,
        diagnostics,
        edge_counter,
    )
    for node in flow_nodes:
        if node.id not in nodes_by_id:
            nodes_by_id[node.id] = node
    sub_graphs.update(flow_subgraphs)

    _auto_wire(list(nodes_by_id.values()), edges, diagnostics)
    input_node = _create_input_node(list(nodes_by_id.values()), edges, diagnostics, edge_counter)
    if input_node is not None:
        nodes_by_id[input_node.id] = input_node

    nodes = list(nodes_by_id.values())
    entry_points = _find_entry_points(nodes, edges)
    if input_node is not None:
        entry_points = [input_node.id]
    exit_points = _find_exit_points(nodes, edges)
    return Graph(
        metadata=GraphMetadata(name=f"{parent_name}_composite"),
        nodes=nodes,
        edges=edges,
        sub_graphs=sub_graphs,
        entry_points=entry_points,
        exit_points=exit_points,
    )


def _build_input_ports(spec: AgentSpec, diagnostics: list[Diagnostic]) -> list[InputPort]:
    base_dir = spec.file_path.parent if spec.file_path else Path.cwd()
    by_name: dict[str, InputPort] = {}
    for port_spec in spec.input_ports:
        schema = _resolve_port_schema(port_spec, base_dir, diagnostics)
        by_name[port_spec.name] = InputPort(
            name=port_spec.name,
            json_schema=schema,
            required=True,
        )

    placeholders = _find_placeholders(spec.prompt_body)
    for placeholder in placeholders:
        if placeholder in by_name:
            continue
        by_name[placeholder] = InputPort(
            name=placeholder,
            json_schema=infer_schema_from_name(placeholder),
            required=True,
        )

    if not by_name:
        by_name[DEFAULT_INPUT_PORT] = InputPort(
            name=DEFAULT_INPUT_PORT,
            json_schema={"type": "object"},
            required=False,
        )
    return list(by_name.values())


def _build_output_ports(spec: AgentSpec, diagnostics: list[Diagnostic]) -> list[OutputPort]:
    base_dir = spec.file_path.parent if spec.file_path else Path.cwd()
    by_name: dict[str, OutputPort] = {}
    for port_spec in spec.output_ports:
        schema = _resolve_port_schema(port_spec, base_dir, diagnostics)
        by_name[port_spec.name] = OutputPort(
            name=port_spec.name,
            json_schema=schema,
        )

    if spec.agent_type == "router":
        if "route" not in by_name:
            by_name["route"] = OutputPort(name="route", json_schema={"type": "string"})
        for route_name in sorted(spec.route_descriptions):
            if route_name not in by_name:
                by_name[route_name] = OutputPort(
                    name=route_name,
                    json_schema={"type": "object"},
                )

    default_name = _default_output_port_for_agent_type(spec.agent_type)
    if default_name not in by_name:
        by_name[default_name] = OutputPort(
            name=default_name,
            json_schema={"type": "string"},
        )
    return list(by_name.values())


def _resolve_port_schema(
    port_spec: PortSpec,
    base_dir: Path,
    diagnostics: list[Diagnostic],
) -> dict[str, Any]:
    if port_spec.schema_path:
        try:
            return load_linked_schema(port_spec.schema_path, base_dir)
        except SchemaLoadError as exc:
            _emit_error(
                diagnostics,
                f"Failed to load schema for port '{port_spec.name}': {exc}",
                source=port_spec.source,
            )
            return {"type": "string"}
    return infer_port_schema(port_spec.name, port_spec.type_annotation)


def _find_placeholders(template: str) -> list[str]:
    return sorted(set(re.findall(r"\{(\w+)\}", template or "")))


def _default_output_port_for_agent_type(agent_type: str) -> str:
    if agent_type == "llm":
        return DEFAULT_OUTPUT_PORTS["llm_operator"]
    if agent_type == "tool":
        return DEFAULT_OUTPUT_PORTS["tool_operator"]
    if agent_type == "code":
        return DEFAULT_OUTPUT_PORTS["code_operator"]
    if agent_type == "router":
        return DEFAULT_OUTPUT_PORTS["router"]
    if agent_type == "human":
        return DEFAULT_OUTPUT_PORTS["human_in_the_loop"]
    if agent_type == "composite":
        return DEFAULT_OUTPUT_PORTS["composite"]
    return "result"


def _default_output_port(node: NodeBase) -> str:
    if node.node_type == "gate":
        gate_mode = getattr(node, "gate_mode", "if_else")
        return "done" if gate_mode == "while" else "true"
    # For composite with "results" (array), prefer it over "result" for ForEach wiring
    if node.node_type == "composite" and any(p.name == "results" for p in node.output_ports):
        return "results"
    mapped = DEFAULT_OUTPUT_PORTS.get(node.node_type)
    if mapped and any(port.name == mapped for port in node.output_ports):
        return mapped
    if node.output_ports:
        return node.output_ports[0].name
    return mapped or "result"


def _default_input_port(node: NodeBase) -> str:
    if node.input_ports:
        return node.input_ports[0].name
    return DEFAULT_INPUT_PORT


def _infer_input_variable_type(ports: list[InputPort]) -> str:
    """Infer InputVariable.type (constrained to string|number|boolean)."""
    types = {port.json_schema.get("type") for port in ports if isinstance(port.json_schema, dict)}
    types.discard(None)
    if "boolean" in types:
        return "boolean"
    if "number" in types or "integer" in types:
        return "number"
    return "string"


def _infer_input_port_schema(ports: list[InputPort]) -> dict[str, Any]:
    """Infer the JSON schema for an auto-generated InputNode output port,
    using the actual target port schemas (not constrained to InputVariable types)."""
    schemas = [port.json_schema for port in ports if isinstance(port.json_schema, dict) and port.json_schema]
    if len(schemas) == 1:
        return dict(schemas[0])
    types = {s.get("type") for s in schemas}
    types.discard(None)
    if len(types) == 1:
        return {"type": next(iter(types))}
    return {"type": "string"}


def _make_data_edge(
    source_node_id: str,
    source_port: str,
    target_node_id: str,
    target_port: str,
    edge_counter: list[int],
    source: SourceLocation | None = None,
) -> DataEdge:
    index = edge_counter[0]
    edge_counter[0] += 1
    return DataEdge(
        id=f"edge_{source_node_id}_{target_node_id}_{index}",
        source_node_id=source_node_id,
        source_port=source_port,
        target_node_id=target_node_id,
        target_port=target_port,
        metadata=_source_metadata(source),
    )


def _find_entry_points(nodes: list[NodeBase], edges: list[DataEdge]) -> list[str]:
    has_incoming = {edge.target_node_id for edge in edges}
    return [node.id for node in nodes if node.id not in has_incoming]


def _find_exit_points(nodes: list[NodeBase], edges: list[DataEdge]) -> list[str]:
    has_outgoing = {edge.source_node_id for edge in edges}
    return [node.id for node in nodes if node.id not in has_outgoing]


def _ensure_unique_id(candidate: str, existing: set[str]) -> str:
    if candidate not in existing:
        return candidate
    suffix = 2
    while f"{candidate}_{suffix}" in existing:
        suffix += 1
    return f"{candidate}_{suffix}"


def _source_metadata(
    source: SourceLocation | None,
    fallback_file: Path | None = None,
) -> dict[str, Any]:
    file_path = source.file if source is not None else fallback_file
    line = source.line if source is not None else 0
    if file_path is None:
        return {}
    return {"source": {"file": str(file_path), "line": line}}


def _is_validation_warning(message: str) -> bool:
    lowered = message.lower()
    return any(pattern in lowered for pattern in _VALIDATION_WARNING_PATTERNS)


def _emit_error(
    diagnostics: list[Diagnostic],
    message: str,
    *,
    source: SourceLocation | None = None,
    source_file: Path | None = None,
    hint: str | None = None,
) -> None:
    diagnostics.append(
        Diagnostic(
            level="error",
            message=message,
            source_file=source_file or (source.file if source else None),
            source_line=source.line if source else 0,
            source_column=source.column if source else 0,
            hint=hint,
        )
    )


def _emit_warning(
    diagnostics: list[Diagnostic],
    message: str,
    *,
    source: SourceLocation | None = None,
    source_file: Path | None = None,
    hint: str | None = None,
) -> None:
    diagnostics.append(
        Diagnostic(
            level="warning",
            message=message,
            source_file=source_file or (source.file if source else None),
            source_line=source.line if source else 0,
            source_column=source.column if source else 0,
            hint=hint,
        )
    )
