"""Shared concierge runtime modules."""

from .command_registry import CommandDescriptor, CommandRegistry, SubcommandDescriptor, get_default_registry
from .classifier import (
    IntentCategory,
    ClassificationResult,
    classify_intent,
    classify_intent_llm,
    extract_search_query_from_send_request,
    search_local_files,
)
from .context_resolver import ProjectContextResolver, ResolvedContext
from .executor import ExecutionResult, ExecutionSelector
from .fan_out import fan_out, fan_out_dict
from .dispatcher import ConcurrentDispatcher
from .handlers import HandlerRegistry, HandlerResult
from .identity import format_bare_prefix, format_prefix, get_bot_name, starts_with_prefix, strip_prefix
from .memory_bridge import ExperienceContext, ReuseRecommendation, WorkflowCandidate, WorkflowMemoryIndex
from .models import ConciergeGoal, ConciergeState, Project, SurfaceMessage, Task, TaskTurn
from .policy import ActionPolicy, BehaviorPolicy, ClarificationRequest, ClarificationResponse, ExecutionPolicy, resolve_policy, validate_terminal_content
from .solver import ExecutionMode, FallbackStep, GoalResolver, PlanBuilder, PlanStep, SolverDecision, TerminalOutcome
from .progress import ProgressReporter
from .project_store import ProjectStore
from .promotion import PromotionProposal, WorkflowPromoter
from .queue import ProjectMessageQueue, QueueDecision
from .resources import MessagePriority, PriorityQueue, ResourceBudget, ResourceTracker, classify_priority
from .runtime import AutonomyLevel, Concierge, build_concierge
from .build_session import BuildIteration, BuildSession, BuildSessionManager, BuildSessionStatus
from .goal_loop import (
    AttemptRecord,
    ComparisonOp,
    CustomEvaluator,
    EvaluationResult,
    Evaluator,
    GoalLoopExecutor,
    GoalLoopState,
    GoalSpec,
    LLMJudgeEvaluator,
    ScriptEvaluator,
    TestSuiteEvaluator,
    handle_goal_command,
    handle_goal_status_command,
    handle_goal_stop_command,
    is_better,
    is_target_met,
)
from .completion_guard import (
    CompletionChecker,
    CompletionReport,
    CompletionStats,
    CompletionStatus,
    Requirement,
    RequirementExtractor,
    augment_response,
    get_stats as get_completion_stats,
    handle_completion_command,
    reset_stats as reset_completion_stats,
    run_completion_check,
)
from .pii_tokenizer import (
    PIISession,
    SensitiveWord,
    SensitiveWordRegistry,
    TokenizingProviderWrapper,
    detokenize,
    handle_pii_command,
    is_pii_enabled,
    tokenize,
)
from .computer_policy import (
    ActionType,
    AuditEntry,
    AuditLog,
    BrowserDomainRule,
    ChunkPolicies,
    ChunkPolicy,
    ComputerControlConfig,
    SessionOverride,
    classify_action,
    is_app_allowed,
    is_domain_allowed,
    requires_approval,
)
from .computer_use import (
    ComputerUseController,
    ComputerUseLeaseManager,
    ObservedElement,
    UIObservation,
    handle_computer_command,
)
from .learning import handle_adaptations_command, handle_corrections_command
from .progress_ux import (
    CheckpointOption,
    CheckpointOptions,
    CLIProgressRenderer,
    EditorProgressRenderer,
    InteractionRequest,
    ProgressPhase,
    ProgressRenderer,
    ProgressSession,
    TelegramProgressRenderer,
    VerbosityLevel,
    WhatsAppProgressRenderer,
    generate_preflight_questions,
    handle_progress_command,
    resolve_verbosity,
)
from .scheduler import (
    DeliveryTarget,
    ScheduleEntry,
    ScheduleHistoryStore,
    ScheduleRunRecord,
    ScheduleStore,
    TaskScheduler,
    TriggerContext,
    compute_next_run,
    handle_schedule_command,
    parse_schedule_add,
    parse_trigger,
)
from .resume import (
    ResumeProtocol,
    TaskSnapshot,
    extract_structured_state,
    handle_resume_command,
    persist_task_state,
    snapshot_from_task,
)
from .follow_up import (
    FollowUpConfig,
    FollowUpDeliveryEngine,
    FollowUpQueue,
    FollowUpTrigger,
    create_run_completion_trigger,
    create_schedule_result_trigger,
    create_stale_task_trigger,
    handle_follow_ups_command,
    load_follow_up_config,
    scan_stale_tasks,
)
from .continuity import (
    ConversationTurn,
    CrossSurfaceContext,
    PresenceTracker,
    ProjectConversationStore,
    SurfacePresence,
    SurfaceRoutingPolicy,
    detect_surface_switch,
    generate_handoff_context,
    handle_sync_command,
    route_message_to_surface,
)

__all__ = [
    "ActionPolicy",
    "AttemptRecord",
    "CommandDescriptor",
    "CommandRegistry",
    "ComparisonOp",
    "CustomEvaluator",
    "SubcommandDescriptor",
    "get_default_registry",
    "AutonomyLevel",
    "BuildIteration",
    "BuildSession",
    "BuildSessionManager",
    "BuildSessionStatus",
    "BehaviorPolicy",
    "ClassificationResult",
    "ClarificationRequest",
    "ClarificationResponse",
    "Concierge",
    "ConciergeGoal",
    "ConciergeState",
    "ConcurrentDispatcher",
    "EvaluationResult",
    "Evaluator",
    "ExecutionMode",
    "ExecutionPolicy",
    "ExecutionResult",
    "ExecutionSelector",
    "ExperienceContext",
    "FallbackStep",
    "fan_out",
    "fan_out_dict",
    "GoalLoopExecutor",
    "GoalLoopState",
    "GoalResolver",
    "GoalSpec",
    "HandlerRegistry",
    "HandlerResult",
    "IntentCategory",
    "LLMJudgeEvaluator",
    "MessagePriority",
    "PriorityQueue",
    "format_bare_prefix",
    "format_prefix",
    "get_bot_name",
    "starts_with_prefix",
    "strip_prefix",
    "PlanBuilder",
    "PlanStep",
    "Project",
    "ProjectContextResolver",
    "ProjectMessageQueue",
    "ProjectStore",
    "ProgressReporter",
    "PromotionProposal",
    "QueueDecision",
    "ResourceBudget",
    "ResourceTracker",
    "ResolvedContext",
    "ScriptEvaluator",
    "ReuseRecommendation",
    "SolverDecision",
    "SurfaceMessage",
    "Task",
    "TaskTurn",
    "TerminalOutcome",
    "TestSuiteEvaluator",
    "WorkflowCandidate",
    "WorkflowMemoryIndex",
    "WorkflowPromoter",
    "CompletionChecker",
    "CompletionReport",
    "CompletionStats",
    "CompletionStatus",
    "Requirement",
    "RequirementExtractor",
    "augment_response",
    "build_concierge",
    "classify_intent",
    "classify_intent_llm",
    "get_completion_stats",
    "handle_completion_command",
    "reset_completion_stats",
    "run_completion_check",
    "classify_priority",
    "extract_search_query_from_send_request",
    "handle_goal_command",
    "handle_goal_status_command",
    "handle_goal_stop_command",
    "is_better",
    "is_target_met",
    "resolve_policy",
    "search_local_files",
    "validate_terminal_content",
    "PIISession",
    "SensitiveWord",
    "SensitiveWordRegistry",
    "TokenizingProviderWrapper",
    "detokenize",
    "handle_pii_command",
    "is_pii_enabled",
    "tokenize",
    "ResumeProtocol",
    "TaskSnapshot",
    "extract_structured_state",
    "handle_resume_command",
    "persist_task_state",
    "snapshot_from_task",
    "DeliveryTarget",
    "ScheduleEntry",
    "ScheduleHistoryStore",
    "ScheduleRunRecord",
    "ScheduleStore",
    "TaskScheduler",
    "TriggerContext",
    "compute_next_run",
    "handle_schedule_command",
    "parse_schedule_add",
    "parse_trigger",
    "CheckpointOption",
    "CheckpointOptions",
    "CLIProgressRenderer",
    "EditorProgressRenderer",
    "InteractionRequest",
    "ProgressPhase",
    "ProgressRenderer",
    "ProgressSession",
    "TelegramProgressRenderer",
    "VerbosityLevel",
    "WhatsAppProgressRenderer",
    "generate_preflight_questions",
    "handle_progress_command",
    "resolve_verbosity",
    "ActionType",
    "AuditEntry",
    "AuditLog",
    "BrowserDomainRule",
    "ChunkPolicies",
    "ChunkPolicy",
    "ComputerControlConfig",
    "ComputerUseController",
    "ComputerUseLeaseManager",
    "ObservedElement",
    "SessionOverride",
    "UIObservation",
    "classify_action",
    "handle_computer_command",
    "is_app_allowed",
    "is_domain_allowed",
    "requires_approval",
    "handle_adaptations_command",
    "handle_corrections_command",
    "ConversationTurn",
    "CrossSurfaceContext",
    "PresenceTracker",
    "ProjectConversationStore",
    "SurfacePresence",
    "SurfaceRoutingPolicy",
    "detect_surface_switch",
    "generate_handoff_context",
    "handle_sync_command",
    "route_message_to_surface",
    "FollowUpConfig",
    "FollowUpDeliveryEngine",
    "FollowUpQueue",
    "FollowUpTrigger",
    "create_run_completion_trigger",
    "create_schedule_result_trigger",
    "create_stale_task_trigger",
    "handle_follow_ups_command",
    "load_follow_up_config",
    "scan_stale_tasks",
]
