"""dan.meta — autonomous workflow planning, execution, and graduated repair."""

from dan.meta.architect import (
    RoutingConfig,
    SystemArchitect,
    SystemManifest,
    SystemPlan,
    SystemValidationResult,
    WorkflowSpec,
)
from dan.meta.authoring import RuntimeAuthor, SkillSpec, ToolSpec, ToolTestResult, ValidationResult
from dan.meta.controller import MetaController, MetaControllerConfig, MetaSession, MetaSessionStatus
from dan.meta.diagnosis import (
    ArtifactMapper,
    ArtifactType,
    AutoFixApplier,
    CorrectionStrategy,
    CorrectionStrategySelector,
    DiagnosisAttempt,
    DiagnosisLoop,
    DiagnosisMetrics,
    DiagnosisResult,
    ErrorArtifact,
    ErrorClassifier,
    GenerationError,
    GenerationErrorType,
    GenerationStage,
    RePromptComposer,
)
from dan.meta.discovery import DiscoveryService, DiscoveryResult
from dan.meta.generation_defaults import (
    DefaultProfile,
    DefaultsEnricher,
    DomainGenerationProfile,
    GenerationDefaults,
    build_domain_prompt_context,
    clear_profile_cache,
    detect_suppressions,
    get_domain_profile,
)
from dan.meta.graph_quality import (
    GraphQualityReport,
    QualityCheck,
    check_node_count,
    check_pattern_presence,
    check_topology,
    check_tool_coverage,
    compute_quality_report,
)
from dan.meta.intent_compiler import COVERAGE_CATALOG, CoverageChecker, CoverageResult, DOMAIN_PATTERN_PREFERENCES, IntentCompiler
from dan.meta.intent_extraction import (
    INTENT_EXTRACTION_SYSTEM_PROMPT,
    INTENT_FEW_SHOT_EXAMPLES,
    build_intent_tool_schema,
)
from dan.meta.intent_schema import StageIntent, StageType, WorkflowIntent
from dan.meta.planner import CodegenDiagnostics, WorkflowPlanner, PlannerOutput
from dan.meta.repair import RepairEscalator, RepairLevel
from dan.meta.self_knowledge import SelfKnowledgeIndex, RetrievedChunk
from dan.meta.structural_mutations import (
    DispatchResult,
    MutationMacroResult,
    dispatch_structural_mutation,
    fan_out_node,
    insert_tool,
    insert_validator,
    parallelize,
    resolve_node,
    summarize_graph,
    unwrap_loop,
    wrap_in_review_loop,
)

__all__ = [
    "ArtifactMapper",
    "ArtifactType",
    "AutoFixApplier",
    "CorrectionStrategy",
    "CorrectionStrategySelector",
    "CodegenDiagnostics",
    "COVERAGE_CATALOG",
    "CoverageChecker",
    "CoverageResult",
    "DOMAIN_PATTERN_PREFERENCES",
    "DefaultProfile",
    "DefaultsEnricher",
    "DiagnosisAttempt",
    "DiagnosisLoop",
    "DiagnosisMetrics",
    "DiagnosisResult",
    "DiscoveryResult",
    "DiscoveryService",
    "DispatchResult",
    "DomainGenerationProfile",
    "ErrorArtifact",
    "ErrorClassifier",
    "GenerationDefaults",
    "GenerationError",
    "GenerationErrorType",
    "GenerationStage",
    "GraphQualityReport",
    "QualityCheck",
    "INTENT_EXTRACTION_SYSTEM_PROMPT",
    "INTENT_FEW_SHOT_EXAMPLES",
    "IntentCompiler",
    "MetaController",
    "MetaControllerConfig",
    "MetaSession",
    "MetaSessionStatus",
    "MutationMacroResult",
    "PlannerOutput",
    "RePromptComposer",
    "RepairEscalator",
    "RepairLevel",
    "RetrievedChunk",
    "RoutingConfig",
    "RuntimeAuthor",
    "SelfKnowledgeIndex",
    "SkillSpec",
    "StageIntent",
    "StageType",
    "SystemArchitect",
    "SystemManifest",
    "SystemPlan",
    "SystemValidationResult",
    "ToolTestResult",
    "ToolSpec",
    "ValidationResult",
    "WorkflowIntent",
    "WorkflowPlanner",
    "WorkflowSpec",
    "build_domain_prompt_context",
    "build_intent_tool_schema",
    "check_node_count",
    "check_pattern_presence",
    "check_topology",
    "check_tool_coverage",
    "compute_quality_report",
    "clear_profile_cache",
    "detect_suppressions",
    "dispatch_structural_mutation",
    "fan_out_node",
    "get_domain_profile",
    "insert_tool",
    "insert_validator",
    "parallelize",
    "resolve_node",
    "summarize_graph",
    "unwrap_loop",
    "wrap_in_review_loop",
]
