"""Public Worker API."""

from importlib import import_module

from dan.worker.core.capabilities import CapabilityCostTier, CapabilityManifest, CapabilitySummary
from dan.worker.core.acquisition import LocalAcquisitionProvider
from dan.worker.core.contracts import (
    AcquisitionFamily,
    AcquisitionPolicy,
    AcquisitionRequest,
    AcquisitionSelection,
    AcquisitionSource,
    AcquisitionStage,
    CommunicationChannel,
    CommunicationChannelKind,
    CommunicationContract,
    ContinuationPayload,
    DiscoveryCatalog,
    DiscoveryItem,
    ExpandedContext,
    MemoryCompactionPolicy,
    MemoryExtractionMode,
    MemoryLayer,
    MemoryRecord,
    MemoryRequest,
    MemorySnapshot,
    MemoryWrite,
    ToolUseContract,
)
from dan.worker.core import (
    CompletionHints as CoreCompletionHints,
    ConstraintSet,
    EvidenceBlock,
    ExecutionRequest,
    OutputContract,
    TrustLabel,
    WorkerCoreExecutor,
    WorkerDefinition,
    WorkerExecutionResult,
)
from dan.worker.core.interfaces import (
    AcquisitionProvider,
    DiscoveryRequest,
    DiscoveryResponse,
    ExpansionRequest,
    ExpansionResponse,
)
from dan.worker.model import (
    AuthorityPolicy,
    ControlFlowConfig,
    ContextBindings,
    ExecutionSemantics,
    LLMHints,
    Worker,
    WorkerAuthority,
    WorkerConfig,
)
from dan.worker.composition import (
    CrossCellTraceLog,
    HandoffExecution,
    execute_cell_handoff,
    make_budget_pressure_signal,
    make_completion_signal,
    make_escalation_signal,
    make_failure_signal,
    make_status_signal,
    make_warning_signal,
)
from dan.worker.outcomes import (
    DEFAULT_EXECUTION_EFFECT_ALIASES,
    DEFAULT_VERIFICATION_ONLY_MARKERS,
    ExecutionEffect,
    StructuredOutcomeView,
    clean_text,
    first_text,
    has_material_structured_outcome,
    infer_execution_effect,
    looks_like_verification_only_summary,
    mutation_claim_requires_evidence,
    normalize_structured_outcome_payload,
    normalize_text_list,
    strip_text,
    structured_outcome_view,
)
from dan.worker.organ import (
    OrganBoundaryContract,
    OrganCellStage,
    OrganEscalationSurface,
    OrganExecution,
    OrganExecutionResult,
    OrganPattern,
    OrganPatternKind,
    build_organ_lead_packet,
    coding_aggregation_organ,
    coding_build_organ,
    deep_research_organ,
    execute_organ_pattern,
    synthesis_organ,
    universal_validator_organ,
)
from dan.worker.organisms import (
    CodingConversationFacts,
    CodingConversationContext,
    CodingConversationController,
    CodingConversationMessage,
    CodingConversationReportSummary,
    CodingConversationReviewDecision,
    CodingConversationTurnDecision,
    CodingOrganism,
    CodingOrganismExecution,
    CodingOrganismResult,
    CodingOrchestratorPlan,
    CodingTask,
    DEFAULT_DEEP_RESEARCH_READER_COUNT,
    DEFAULT_LIVE_ORGANISM_TOOL_IDS,
    DEFAULT_REFERENCE_ACCEPTANCE_CRITERIA,
    DEFAULT_REFERENCE_EVIDENCE_SUMMARIES,
    DEFAULT_REFERENCE_HARD_CONSTRAINTS,
    DEFAULT_REFERENCE_OBJECTIVE,
    DEFAULT_REFERENCE_SOFT_CONSTRAINTS,
    DEFAULT_REFERENCE_VALIDATION_COMMANDS,
    DeepResearchOrganDemoReport,
    MAX_DEEP_RESEARCH_READERS,
    MIN_DEEP_RESEARCH_READERS,
    OrganismObservability,
    OrganismStageRecord,
    ProjectExecutionOrganism,
    ProjectExecutionOrganismExecution,
    ProjectExecutionOrganismResult,
    ProjectExecutionTask,
    ReferenceOrganismDemoReport,
    ResearchConversationFacts,
    ResearchConversationContext,
    ResearchConversationController,
    ResearchConversationMessage,
    ResearchConversationReportSummary,
    ResearchConversationReviewDecision,
    ResearchConversationTurnDecision,
    available_local_organism_tools,
    build_research_orchestrator_worker,
    build_reference_organism_demo_task,
    coding_execution_organism,
    execute_coding_organism,
    execute_project_execution_organism,
    project_execution_reference_organism,
    recommended_deep_research_reader_briefs,
    recommended_deep_research_reader_count,
    resolve_deep_research_reader_briefs_for_task,
    resolve_deep_research_reader_count,
    run_deep_research_organ_demo,
    run_deep_research_organ_live,
    run_reference_organism_demo,
    run_reference_organism_live,
)
from dan.worker.tissue import (
    TissueBudgetEnvelope,
    TissueExecution,
    TissueExecutionResult,
    TissueMember,
    TissueMergeMode,
    TissuePattern,
    TissuePatternKind,
    TissuePoolLimits,
    TissueQuorumDecision,
    TissueQuorumPolicy,
    build_tissue_member_packet,
    execute_tissue_pattern,
    parallel_worker_pool,
    retrieval_enrichment_pool,
    review_quorum_pool,
)
from dan.worker.presets import (
    BRIDGED_LEGACY_NODE_TYPES,
    EXPLICIT_NON_BRIDGED_LEGACY_NODE_TYPES,
    convert_graph,
    legacy_to_worker,
    supports_legacy_conversion,
    validate_conversion,
    worker_to_legacy,
)
from dan.worker.signaling import (
    BroadcastScope,
    BudgetPressureSignal,
    CellAddress,
    CellAuthorityLimits,
    CellBudgetLimits,
    CellHandoffPacket,
    CompletionSignal,
    ContinuationHooks,
    EscalationSignal,
    EvidenceRef,
    FailureSignal,
    HandoffTask,
    SignalTrace,
    StatusSignal,
    SupervisorySignal,
    SupervisorySignalBase,
    WarningSignal,
)
from dan.worker.roles import gate, llm_agent, manager, observer, reviewer, role, router, script, tool_runner, validator

__all__ = [
    "AcquisitionFamily",
    "AcquisitionPolicy",
    "AcquisitionProvider",
    "AcquisitionRequest",
    "AcquisitionSelection",
    "AcquisitionSource",
    "AcquisitionStage",
    "AuthorityPolicy",
    "BRIDGED_LEGACY_NODE_TYPES",
    "BroadcastScope",
    "BudgetPressureSignal",
    "CapabilityCostTier",
    "CapabilityManifest",
    "CapabilitySummary",
    "CellAddress",
    "CellAuthorityLimits",
    "CellBudgetLimits",
    "CodingConversationFacts",
    "CodingConversationContext",
    "CodingConversationController",
    "CodingConversationMessage",
    "CodingConversationReportSummary",
    "CodingConversationReviewDecision",
    "CodingConversationTurnDecision",
    "CodingOrganism",
    "CodingOrganismExecution",
    "CodingOrganismResult",
    "CodingOrchestratorPlan",
    "CodingTask",
    "CellHandoffPacket",
    "CommunicationChannel",
    "CommunicationChannelKind",
    "CommunicationContract",
    "CompletionSignal",
    "ConstraintSet",
    "ControlFlowConfig",
    "CoreCompletionHints",
    "ContinuationPayload",
    "ContinuationHooks",
    "CrossCellTraceLog",
    "DEFAULT_DEEP_RESEARCH_READER_COUNT",
    "DiscoveryCatalog",
    "DiscoveryItem",
    "ContextBindings",
    "DEFAULT_LIVE_ORGANISM_TOOL_IDS",
    "MAX_DEEP_RESEARCH_READERS",
    "MIN_DEEP_RESEARCH_READERS",
    "DEFAULT_REFERENCE_ACCEPTANCE_CRITERIA",
    "DEFAULT_REFERENCE_EVIDENCE_SUMMARIES",
    "DEFAULT_REFERENCE_HARD_CONSTRAINTS",
    "DEFAULT_REFERENCE_OBJECTIVE",
    "DEFAULT_REFERENCE_SOFT_CONSTRAINTS",
    "DEFAULT_REFERENCE_VALIDATION_COMMANDS",
    "DeepResearchOrganDemoReport",
    "DurableAgentPolicy",
    "DurableAgentRunner",
    "DurableAgentSessionState",
    "DurableAgentTurnResult",
    "DurableBackgroundTask",
    "DurableMailboxMessage",
    "EvidenceBlock",
    "EscalationSignal",
    "ExecutionEffect",
    "EvidenceRef",
    "EXPLICIT_NON_BRIDGED_LEGACY_NODE_TYPES",
    "ExpandedContext",
    "ExecutionSemantics",
    "ExecutionRequest",
    "ExpansionRequest",
    "ExpansionResponse",
    "FailureSignal",
    "HandoffExecution",
    "HandoffTask",
    "LLMHints",
    "LocalAcquisitionProvider",
    "MemoryCompactionPolicy",
    "MemoryExtractionMode",
    "MemoryLayer",
    "MemoryRecord",
    "MemoryRequest",
    "MemorySnapshot",
    "MemoryWrite",
    "OrganBoundaryContract",
    "OrganCellStage",
    "OrganEscalationSurface",
    "OrganExecution",
    "OrganExecutionResult",
    "OrganPattern",
    "OrganPatternKind",
    "OrganismObservability",
    "OrganismStageRecord",
    "OutputContract",
    "ProjectExecutionOrganism",
    "ProjectExecutionOrganismExecution",
    "ProjectExecutionOrganismResult",
    "ProjectExecutionTask",
    "ReferenceOrganismDemoReport",
    "ResearchConversationFacts",
    "ResearchConversationContext",
    "ResearchConversationController",
    "ResearchConversationMessage",
    "ResearchConversationReportSummary",
    "ResearchConversationReviewDecision",
    "ResearchConversationTurnDecision",
    "StructuredOutcomeView",
    "SignalTrace",
    "StatusSignal",
    "SupervisorySignal",
    "SupervisorySignalBase",
    "TissueBudgetEnvelope",
    "TissueExecution",
    "TissueExecutionResult",
    "TissueMember",
    "TissueMergeMode",
    "TissuePattern",
    "TissuePatternKind",
    "TissuePoolLimits",
    "TissueQuorumDecision",
    "TissueQuorumPolicy",
    "ToolUseContract",
    "TrustLabel",
    "WarningSignal",
    "Worker",
    "WorkerAuthority",
    "WorkerConfig",
    "WorkerCoreExecutor",
    "WorkerDefinition",
    "DiscoveryRequest",
    "DiscoveryResponse",
    "WorkerExecutionResult",
    "build_organ_lead_packet",
    "available_local_organism_tools",
    "build_research_orchestrator_worker",
    "build_reference_organism_demo_task",
    "clean_text",
    "coding_execution_organism",
    "coding_aggregation_organ",
    "coding_build_organ",
    "convert_graph",
    "deep_research_organ",
    "execute_cell_handoff",
    "execute_organ_pattern",
    "execute_coding_organism",
    "execute_project_execution_organism",
    "execute_tissue_pattern",
    "DEFAULT_EXECUTION_EFFECT_ALIASES",
    "DEFAULT_VERIFICATION_ONLY_MARKERS",
    "first_text",
    "gate",
    "has_material_structured_outcome",
    "infer_execution_effect",
    "legacy_to_worker",
    "llm_agent",
    "looks_like_verification_only_summary",
    "manager",
    "make_budget_pressure_signal",
    "make_completion_signal",
    "make_escalation_signal",
    "make_failure_signal",
    "make_status_signal",
    "make_warning_signal",
    "observer",
    "parallel_worker_pool",
    "project_execution_reference_organism",
    "recommended_deep_research_reader_briefs",
    "recommended_deep_research_reader_count",
    "resolve_deep_research_reader_briefs_for_task",
    "resolve_deep_research_reader_count",
    "mutation_claim_requires_evidence",
    "normalize_structured_outcome_payload",
    "normalize_text_list",
    "retrieval_enrichment_pool",
    "reviewer",
    "review_quorum_pool",
    "role",
    "router",
    "script",
    "StandaloneObservability",
    "StandaloneRunAttempt",
    "StandaloneRunEvent",
    "StandaloneRunPolicy",
    "StandaloneRunResult",
    "StandaloneSessionState",
    "StandaloneWorkerRunner",
    "supports_legacy_conversion",
    "synthesis_organ",
    "tool_runner",
    "universal_validator_organ",
    "validator",
    "validate_conversion",
    "worker_to_legacy",
    "build_tissue_member_packet",
    "run_deep_research_organ_demo",
    "run_deep_research_organ_live",
    "run_reference_organism_demo",
    "run_reference_organism_live",
    "strip_text",
    "structured_outcome_view",
]


def __getattr__(name: str):
    lazy_imports = {
        "WorkerExecutor": ("dan.worker.executor", "WorkerExecutor"),
        "StandaloneObservability": ("dan.worker.runner", "StandaloneObservability"),
        "StandaloneRunAttempt": ("dan.worker.runner", "StandaloneRunAttempt"),
        "StandaloneRunEvent": ("dan.worker.runner", "StandaloneRunEvent"),
        "StandaloneRunPolicy": ("dan.worker.runner", "StandaloneRunPolicy"),
        "StandaloneRunResult": ("dan.worker.runner", "StandaloneRunResult"),
        "StandaloneSessionState": ("dan.worker.runner", "StandaloneSessionState"),
        "StandaloneWorkerRunner": ("dan.worker.runner", "StandaloneWorkerRunner"),
        "DurableAgentPolicy": ("dan.worker.runner", "DurableAgentPolicy"),
        "DurableAgentRunner": ("dan.worker.runner", "DurableAgentRunner"),
        "DurableAgentSessionState": ("dan.worker.runner", "DurableAgentSessionState"),
        "DurableAgentTurnResult": ("dan.worker.runner", "DurableAgentTurnResult"),
        "DurableBackgroundTask": ("dan.worker.runner", "DurableBackgroundTask"),
        "DurableMailboxMessage": ("dan.worker.runner", "DurableMailboxMessage"),
    }
    if name in lazy_imports:
        module_name, attr_name = lazy_imports[name]
        module = import_module(module_name)
        return getattr(module, attr_name)
    raise AttributeError(name)
