"""Public Worker API."""

from importlib import import_module

from dan.worker.core.capabilities import CapabilityCostTier, CapabilityManifest, CapabilitySummary
from dan.worker.core.acquisition import LocalAcquisitionProvider
from dan.worker.core.contracts import (
    AcquisitionFamily,
    AcquisitionPolicy,
    AcquisitionRequest,
    AcquisitionSelection,
    AcquisitionSource,
    AcquisitionStage,
    CommunicationChannel,
    CommunicationChannelKind,
    CommunicationContract,
    ContinuationPayload,
    DiscoveryCatalog,
    DiscoveryItem,
    ExpandedContext,
    MemoryCompactionPolicy,
    MemoryExtractionMode,
    MemoryLayer,
    MemoryRecord,
    MemoryRequest,
    MemorySnapshot,
    MemoryWrite,
    ToolUseContract,
)
from dan.worker.core import (
    CompletionHints as CoreCompletionHints,
    ConstraintSet,
    EvidenceBlock,
    ExecutionRequest,
    OutputContract,
    TrustLabel,
    WorkerCoreExecutor,
    WorkerDefinition,
    WorkerExecutionResult,
)
from dan.worker.core.interfaces import (
    AcquisitionProvider,
    DiscoveryRequest,
    DiscoveryResponse,
    ExpansionRequest,
    ExpansionResponse,
)
from dan.worker.model import (
    AuthorityPolicy,
    ControlFlowConfig,
    ContextBindings,
    ExecutionSemantics,
    LLMHints,
    Worker,
    WorkerAuthority,
    WorkerConfig,
)
from dan.worker.composition import (
    CrossCellTraceLog,
    HandoffExecution,
    execute_cell_handoff,
    make_budget_pressure_signal,
    make_completion_signal,
    make_escalation_signal,
    make_failure_signal,
    make_status_signal,
    make_warning_signal,
)
from dan.worker.organ import (
    OrganBoundaryContract,
    OrganCellStage,
    OrganEscalationSurface,
    OrganExecution,
    OrganExecutionResult,
    OrganPattern,
    OrganPatternKind,
    build_organ_lead_packet,
    coding_aggregation_organ,
    coding_build_organ,
    deep_research_organ,
    execute_organ_pattern,
    synthesis_organ,
    universal_validator_organ,
)
from dan.worker.organisms import (
    CodingOrganism,
    CodingOrganismExecution,
    CodingOrganismResult,
    CodingOrchestratorPlan,
    CodingTask,
    DEFAULT_LIVE_ORGANISM_TOOL_IDS,
    DEFAULT_REFERENCE_ACCEPTANCE_CRITERIA,
    DEFAULT_REFERENCE_EVIDENCE_SUMMARIES,
    DEFAULT_REFERENCE_HARD_CONSTRAINTS,
    DEFAULT_REFERENCE_OBJECTIVE,
    DEFAULT_REFERENCE_SOFT_CONSTRAINTS,
    DEFAULT_REFERENCE_VALIDATION_COMMANDS,
    OrganismObservability,
    OrganismStageRecord,
    ProjectExecutionOrganism,
    ProjectExecutionOrganismExecution,
    ProjectExecutionOrganismResult,
    ProjectExecutionTask,
    ReferenceOrganismDemoReport,
    available_local_organism_tools,
    build_reference_organism_demo_task,
    coding_execution_organism,
    execute_coding_organism,
    execute_project_execution_organism,
    project_execution_reference_organism,
    run_reference_organism_demo,
    run_reference_organism_live,
)
from dan.worker.tissue import (
    TissueBudgetEnvelope,
    TissueExecution,
    TissueExecutionResult,
    TissueMember,
    TissueMergeMode,
    TissuePattern,
    TissuePatternKind,
    TissuePoolLimits,
    TissueQuorumDecision,
    TissueQuorumPolicy,
    build_tissue_member_packet,
    execute_tissue_pattern,
    parallel_worker_pool,
    retrieval_enrichment_pool,
    review_quorum_pool,
)
from dan.worker.presets import (
    BRIDGED_LEGACY_NODE_TYPES,
    EXPLICIT_NON_BRIDGED_LEGACY_NODE_TYPES,
    convert_graph,
    legacy_to_worker,
    supports_legacy_conversion,
    validate_conversion,
    worker_to_legacy,
)
from dan.worker.signaling import (
    BroadcastScope,
    BudgetPressureSignal,
    CellAddress,
    CellAuthorityLimits,
    CellBudgetLimits,
    CellHandoffPacket,
    CompletionSignal,
    ContinuationHooks,
    EscalationSignal,
    EvidenceRef,
    FailureSignal,
    HandoffTask,
    SignalTrace,
    StatusSignal,
    SupervisorySignal,
    SupervisorySignalBase,
    WarningSignal,
)
from dan.worker.roles import gate, llm_agent, manager, observer, reviewer, role, router, script, tool_runner, validator

__all__ = [
    "AcquisitionFamily",
    "AcquisitionPolicy",
    "AcquisitionProvider",
    "AcquisitionRequest",
    "AcquisitionSelection",
    "AcquisitionSource",
    "AcquisitionStage",
    "AuthorityPolicy",
    "BRIDGED_LEGACY_NODE_TYPES",
    "BroadcastScope",
    "BudgetPressureSignal",
    "CapabilityCostTier",
    "CapabilityManifest",
    "CapabilitySummary",
    "CellAddress",
    "CellAuthorityLimits",
    "CellBudgetLimits",
    "CodingOrganism",
    "CodingOrganismExecution",
    "CodingOrganismResult",
    "CodingOrchestratorPlan",
    "CodingTask",
    "CellHandoffPacket",
    "CommunicationChannel",
    "CommunicationChannelKind",
    "CommunicationContract",
    "CompletionSignal",
    "ConstraintSet",
    "ControlFlowConfig",
    "CoreCompletionHints",
    "ContinuationPayload",
    "ContinuationHooks",
    "CrossCellTraceLog",
    "DiscoveryCatalog",
    "DiscoveryItem",
    "ContextBindings",
    "DEFAULT_LIVE_ORGANISM_TOOL_IDS",
    "DEFAULT_REFERENCE_ACCEPTANCE_CRITERIA",
    "DEFAULT_REFERENCE_EVIDENCE_SUMMARIES",
    "DEFAULT_REFERENCE_HARD_CONSTRAINTS",
    "DEFAULT_REFERENCE_OBJECTIVE",
    "DEFAULT_REFERENCE_SOFT_CONSTRAINTS",
    "DEFAULT_REFERENCE_VALIDATION_COMMANDS",
    "EvidenceBlock",
    "EscalationSignal",
    "EvidenceRef",
    "EXPLICIT_NON_BRIDGED_LEGACY_NODE_TYPES",
    "ExpandedContext",
    "ExecutionSemantics",
    "ExecutionRequest",
    "ExpansionRequest",
    "ExpansionResponse",
    "FailureSignal",
    "HandoffExecution",
    "HandoffTask",
    "LLMHints",
    "LocalAcquisitionProvider",
    "MemoryCompactionPolicy",
    "MemoryExtractionMode",
    "MemoryLayer",
    "MemoryRecord",
    "MemoryRequest",
    "MemorySnapshot",
    "MemoryWrite",
    "OrganBoundaryContract",
    "OrganCellStage",
    "OrganEscalationSurface",
    "OrganExecution",
    "OrganExecutionResult",
    "OrganPattern",
    "OrganPatternKind",
    "OrganismObservability",
    "OrganismStageRecord",
    "OutputContract",
    "ProjectExecutionOrganism",
    "ProjectExecutionOrganismExecution",
    "ProjectExecutionOrganismResult",
    "ProjectExecutionTask",
    "ReferenceOrganismDemoReport",
    "SignalTrace",
    "StatusSignal",
    "SupervisorySignal",
    "SupervisorySignalBase",
    "TissueBudgetEnvelope",
    "TissueExecution",
    "TissueExecutionResult",
    "TissueMember",
    "TissueMergeMode",
    "TissuePattern",
    "TissuePatternKind",
    "TissuePoolLimits",
    "TissueQuorumDecision",
    "TissueQuorumPolicy",
    "ToolUseContract",
    "TrustLabel",
    "WarningSignal",
    "Worker",
    "WorkerAuthority",
    "WorkerConfig",
    "WorkerCoreExecutor",
    "WorkerDefinition",
    "DiscoveryRequest",
    "DiscoveryResponse",
    "WorkerExecutionResult",
    "build_organ_lead_packet",
    "available_local_organism_tools",
    "build_reference_organism_demo_task",
    "coding_execution_organism",
    "coding_aggregation_organ",
    "coding_build_organ",
    "convert_graph",
    "deep_research_organ",
    "execute_cell_handoff",
    "execute_organ_pattern",
    "execute_coding_organism",
    "execute_project_execution_organism",
    "execute_tissue_pattern",
    "gate",
    "legacy_to_worker",
    "llm_agent",
    "manager",
    "make_budget_pressure_signal",
    "make_completion_signal",
    "make_escalation_signal",
    "make_failure_signal",
    "make_status_signal",
    "make_warning_signal",
    "observer",
    "parallel_worker_pool",
    "project_execution_reference_organism",
    "retrieval_enrichment_pool",
    "reviewer",
    "review_quorum_pool",
    "role",
    "router",
    "script",
    "StandaloneObservability",
    "StandaloneRunAttempt",
    "StandaloneRunEvent",
    "StandaloneRunPolicy",
    "StandaloneRunResult",
    "StandaloneSessionState",
    "StandaloneWorkerRunner",
    "supports_legacy_conversion",
    "synthesis_organ",
    "tool_runner",
    "universal_validator_organ",
    "validator",
    "validate_conversion",
    "worker_to_legacy",
    "build_tissue_member_packet",
    "run_reference_organism_demo",
    "run_reference_organism_live",
]


def __getattr__(name: str):
    lazy_imports = {
        "WorkerExecutor": ("dan.worker.executor", "WorkerExecutor"),
        "StandaloneObservability": ("dan.worker.runner", "StandaloneObservability"),
        "StandaloneRunAttempt": ("dan.worker.runner", "StandaloneRunAttempt"),
        "StandaloneRunEvent": ("dan.worker.runner", "StandaloneRunEvent"),
        "StandaloneRunPolicy": ("dan.worker.runner", "StandaloneRunPolicy"),
        "StandaloneRunResult": ("dan.worker.runner", "StandaloneRunResult"),
        "StandaloneSessionState": ("dan.worker.runner", "StandaloneSessionState"),
        "StandaloneWorkerRunner": ("dan.worker.runner", "StandaloneWorkerRunner"),
    }
    if name in lazy_imports:
        module_name, attr_name = lazy_imports[name]
        module = import_module(module_name)
        return getattr(module, attr_name)
    raise AttributeError(name)
