"""FastAPI application — graph CRUD, run management, and WebSocket events."""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import shutil
import tempfile
import urllib.parse
import urllib.request
import zipfile
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

load_dotenv()

from fastapi import FastAPI, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

from dan.builder.decompiler import decompile as decompile_to_python
from dan.engine.executor import EngineConfig
from dan.executors.tool import ToolRegistry
from dan.loader.decompiler import decompile_to_markdown
from dan.models.graph import Graph
from dan.server.graph_store import GraphStore
from dan.server.run_manager import RunManager
from dan.validation.graph import validate_graph

logger = logging.getLogger(__name__)


def _require_run_manager() -> RunManager:
    if _run_manager is None:
        raise HTTPException(status_code=503, detail="Server not fully initialised")
    return _run_manager

_graphs_dir = os.environ.get("DAN_GRAPHS_DIR", "./graphs")
_graph_store = GraphStore(base_dir=_graphs_dir)
_run_manager: RunManager | None = None


def _get_engine_config() -> EngineConfig:
    from dan.providers import ProviderConfig

    providers: dict[str, ProviderConfig] = {}

    openai_key = os.environ.get("DAN_OPENAI_API_KEY", "")
    if openai_key:
        providers["openai"] = ProviderConfig(api_key=openai_key)

    anthropic_key = os.environ.get("DAN_ANTHROPIC_API_KEY", "")
    if anthropic_key:
        providers["anthropic"] = ProviderConfig(api_key=anthropic_key)

    google_key = os.environ.get("DAN_GOOGLE_API_KEY", "")
    if google_key:
        providers["google"] = ProviderConfig(api_key=google_key)

    return EngineConfig(
        llm_base_url=os.environ.get("DAN_LLM_BASE_URL", "https://api.vectorengine.ai/v1"),
        llm_api_key=os.environ.get("DAN_LLM_API_KEY", os.environ.get("LLM_API_KEY", "")),
        llm_default_model=os.environ.get("DAN_LLM_MODEL", "claude-sonnet-4-6"),
        checkpoint_dir=os.environ.get("DAN_CHECKPOINT_DIR", "./checkpoints"),
        checkpoint_enabled=True,
        providers=providers,
    )


# -- Built-in tools available to all server-side runs -------------------------

def _slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:80]


INFORMS3_CLS_URLS = (
    "https://raw.githubusercontent.com/dengfaheng/latex-INFORMS-journals-template/main/ts/informs3.cls",
)

_CITE_PATTERN = re.compile(
    r"\\cite[a-zA-Z*]*\s*(?:\[[^\]]*\]\s*)?(?:\[[^\]]*\]\s*)?\{([^}]*)\}"
)
_BIB_ENTRY_PATTERN = re.compile(r"@\w+\s*\{\s*([^,\s]+)\s*,", re.IGNORECASE)


def _extract_citation_keys(tex_content: str) -> set[str]:
    keys: set[str] = set()
    for raw in _CITE_PATTERN.findall(tex_content or ""):
        for part in raw.split(","):
            key = part.strip()
            if key:
                keys.add(key)
    return keys


def _extract_bib_keys(bibtex: str) -> set[str]:
    return {m.strip() for m in _BIB_ENTRY_PATTERN.findall(bibtex or "") if m.strip()}


def _build_placeholder_bib_entries(keys: list[str]) -> str:
    entries: list[str] = []
    for key in keys:
        entries.append(
            "\n".join(
                [
                    f"@misc{{{key},",
                    "  author = {Unknown},",
                    f"  title = {{Placeholder reference for {key}}},",
                    "  year = {2024},",
                    "  note = {Auto-generated by compile_latex for missing citation key}",
                    "}",
                ]
            )
        )
    return "\n\n".join(entries)


def _normalize_latex_content(content: str) -> str:
    normalized = content or ""
    normalized = normalized.replace(
        r"\bibliographystyle{informs2014}",
        r"\bibliographystyle{plainnat}",
    )

    if r"\usepackage{hyperref}" not in normalized:
        if r"\usepackage{natbib}" in normalized:
            normalized = normalized.replace(
                r"\usepackage{natbib}",
                r"\usepackage{natbib}" + "\n" + r"\usepackage{hyperref}",
                1,
            )
        elif r"\begin{document}" in normalized:
            normalized = normalized.replace(
                r"\begin{document}",
                r"\usepackage{hyperref}" + "\n" + r"\begin{document}",
                1,
            )

    if r"\providecommand{\newblock}{}" not in normalized:
        if r"\usepackage{hyperref}" in normalized:
            normalized = normalized.replace(
                r"\usepackage{hyperref}",
                r"\usepackage{hyperref}" + "\n" + r"\providecommand{\newblock}{}",
                1,
            )
        elif r"\usepackage{natbib}" in normalized:
            normalized = normalized.replace(
                r"\usepackage{natbib}",
                r"\usepackage{natbib}" + "\n" + r"\providecommand{\newblock}{}",
                1,
            )
        elif r"\begin{document}" in normalized:
            normalized = normalized.replace(
                r"\begin{document}",
                r"\providecommand{\newblock}{}" + "\n" + r"\begin{document}",
                1,
            )
    return normalized


async def _ensure_informs3_cls(output_dir: Path) -> tuple[bool, str]:
    target = output_dir / "informs3.cls"
    if target.exists():
        return True, "informs3.cls found in output/"

    project_copy = Path.cwd() / "informs3.cls"
    if project_copy.exists():
        shutil.copy2(project_copy, target)
        return True, "Copied informs3.cls from project root"

    last_error = ""
    for url in INFORMS3_CLS_URLS:
        try:
            def _download() -> str:
                req = urllib.request.Request(
                    url,
                    headers={"User-Agent": "deep-agent-network/0.1"},
                )
                with urllib.request.urlopen(req, timeout=20) as resp:
                    return resp.read().decode("utf-8", errors="replace")

            content = await asyncio.to_thread(_download)
            if "informs3" not in content.lower():
                raise RuntimeError("Downloaded content does not look like informs3.cls")
            target.write_text(content, encoding="utf-8")
            return True, f"Downloaded informs3.cls from {url}"
        except Exception as exc:
            last_error = str(exc)

    return False, f"Could not fetch informs3.cls automatically ({last_error})"


def _http_get_json(url: str, *, timeout: int = 30) -> dict[str, Any]:
    req = urllib.request.Request(url, headers={"User-Agent": "deep-agent-network/0.1"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        raw = resp.read().decode("utf-8", errors="replace")
    return json.loads(raw)


async def _run_command(cmd: list[str], cwd: Path) -> tuple[int, str]:
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        cwd=str(cwd),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )
    stdout, _ = await proc.communicate()
    out = stdout.decode("utf-8", errors="replace") if stdout else ""
    return proc.returncode, out


async def _save_paper(
    content: str,
    title: str,
    bibtex: str = "",
    pdf_path: str = "",
    compile_log: str = "",
    output_dir: str = "output",
    **kwargs: Any,
) -> dict[str, Any]:
    """Save the final paper as tex/bib/pdf artifacts."""
    output_dir = Path(output_dir)
    output_dir.mkdir(exist_ok=True)
    slug = _slugify(title)
    tex_path = output_dir / f"{slug}.tex"
    bib_path = output_dir / f"{slug}.bib"
    log_path = output_dir / f"{slug}.compile.log.txt"

    tex_path.write_text(content, encoding="utf-8")
    bib_path.write_text(bibtex, encoding="utf-8")
    log_path.write_text(compile_log or "", encoding="utf-8")

    final_pdf_path = output_dir / f"{slug}.pdf"
    if pdf_path and Path(pdf_path).exists():
        source = Path(pdf_path)
        if source.resolve() != final_pdf_path.resolve():
            shutil.copy2(source, final_pdf_path)

    saved_path = str(final_pdf_path) if final_pdf_path.exists() else str(tex_path)
    return {
        "saved_path": saved_path,
        "title": title,
        "tex_path": str(tex_path),
        "bib_path": str(bib_path),
        "pdf_path": str(final_pdf_path) if final_pdf_path.exists() else "",
        "compile_log_path": str(log_path),
    }


async def _search_papers(
    query: str,
    num_results: int = 8,
    aspect: str = "",
    **kwargs: Any,
) -> dict[str, Any]:
    fields = "title,year,venue,authors,citationCount,externalIds,paperId,abstract"
    params = urllib.parse.urlencode(
        {"query": query, "limit": max(1, min(int(num_results), 20)), "fields": fields}
    )
    url = f"https://api.semanticscholar.org/graph/v1/paper/search?{params}"
    papers: list[dict[str, Any]] = []
    error_text = ""
    try:
        data = await asyncio.to_thread(_http_get_json, url)
        for row in data.get("data", []):
            if not isinstance(row, dict):
                continue
            ext = row.get("externalIds") or {}
            if not isinstance(ext, dict):
                ext = {}
            papers.append(
                {
                    "title": str(row.get("title", "")),
                    "year": row.get("year"),
                    "venue": str(row.get("venue", "")),
                    "abstract": str(row.get("abstract", "")),
                    "citation_count": int(row.get("citationCount", 0) or 0),
                    "paper_id": str(row.get("paperId", "")),
                    "doi": str(ext.get("DOI", "")),
                }
            )
    except Exception as exc:
        error_text = str(exc)

    return {
        "aspect": aspect,
        "query": query,
        "papers": papers,
        "paper_count": len(papers),
        "error": error_text,
    }


async def _citation_verifier(key_papers: list[Any] | None = None, **kwargs: Any) -> dict[str, Any]:
    papers = key_papers if isinstance(key_papers, list) else []
    verified: list[dict[str, Any]] = []
    invalid: list[dict[str, Any]] = []
    seen_titles: set[str] = set()
    for row in papers:
        if not isinstance(row, dict):
            invalid.append({"paper": str(row), "reason": "Not an object"})
            continue
        title = str(row.get("title", "")).strip()
        if not title:
            invalid.append({"paper": row, "reason": "Missing title"})
            continue
        key = re.sub(r"\s+", " ", title.lower())
        if key in seen_titles:
            continue
        seen_titles.add(key)
        doi = str(row.get("doi", "")).strip()
        paper_id = str(row.get("paper_id", "")).strip() or str(row.get("paperId", "")).strip()
        if doi or paper_id:
            verified.append(
                {
                    "title": title,
                    "year": row.get("year"),
                    "venue": row.get("venue", ""),
                    "doi": doi,
                    "paper_id": paper_id,
                }
            )
        else:
            invalid.append({"paper": row, "reason": "Missing DOI/paper_id"})
    return {
        "verified_papers": verified,
        "invalid_citations": invalid,
        "verification_notes": f"Verified {len(verified)}; invalid {len(invalid)}.",
    }


async def _check_latex_deps(template_dir: str = "output", **kwargs: Any) -> dict[str, Any]:
    missing_cmds = [cmd for cmd in ("pdflatex", "bibtex") if shutil.which(cmd) is None]
    template_candidates = [Path.cwd(), Path(template_dir)]
    has_cls = any((p / "informs3.cls").exists() for p in template_candidates)
    missing_templates = []
    if not has_cls:
        missing_templates.append("informs3.cls")
    # informs3.cls can be auto-fetched during compile_latex(), so dependency
    # readiness here only requires TeX commands.
    deps_ok = not missing_cmds
    msg = ""
    if missing_cmds:
        msg = (
            f"Missing commands={missing_cmds}. Install TeX binaries first."
        )
    elif missing_templates:
        msg = (
            "informs3.cls not found locally. compile_latex will try to download it "
            "into output/ automatically."
        )
    return {
        "deps_ok": deps_ok,
        "missing_commands": missing_cmds,
        "missing_templates": missing_templates,
        "dependency_message": msg or "LaTeX dependencies are ready.",
    }


async def _compile_latex(
    content: str,
    title: str,
    bibtex: str = "",
    output_dir: str = "output",
    **kwargs: Any,
) -> dict[str, Any]:
    out_dir = Path(output_dir)
    out_dir.mkdir(exist_ok=True, parents=True)
    slug = _slugify(title)
    tex_filename = f"{slug}.tex"
    tex_path = out_dir / tex_filename
    bib_path = out_dir / f"{slug}.bib"
    references_bib = out_dir / "references.bib"

    notes: list[str] = []

    template_ok, template_note = await _ensure_informs3_cls(out_dir)
    notes.append(template_note)
    if not template_ok:
        notes.append(
            "Compile may fail if informs3.cls is unavailable in your TeX tree."
        )

    normalized_content = _normalize_latex_content(content)
    tex_path.write_text(normalized_content, encoding="utf-8")

    cited_keys = _extract_citation_keys(normalized_content)
    existing_keys = _extract_bib_keys(bibtex)
    missing_keys = sorted(cited_keys - existing_keys)

    effective_bibtex = bibtex.strip()
    if missing_keys:
        placeholders = _build_placeholder_bib_entries(missing_keys)
        effective_bibtex = (
            f"{effective_bibtex}\n\n{placeholders}" if effective_bibtex else placeholders
        )
        notes.append(
            "Auto-added placeholder BibTeX entries for missing keys: "
            + ", ".join(missing_keys[:20])
            + (" ..." if len(missing_keys) > 20 else "")
        )

    if effective_bibtex:
        bib_path.write_text(effective_bibtex, encoding="utf-8")
        references_bib.write_text(effective_bibtex, encoding="utf-8")

    if shutil.which("pdflatex") is None:
        return {
            "compile_success": False,
            "pdf_path": "",
            "compile_log": "\n".join(notes + ["pdflatex not found."]),
            "tex_path": str(tex_path),
            "bib_path": str(bib_path) if bib_path.exists() else "",
        }

    logs: list[str] = []
    success = True
    rc, out = await _run_command(
        ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_filename],
        out_dir,
    )
    logs.append(out)
    if rc != 0:
        success = False
    if success and bibtex and shutil.which("bibtex") is not None:
        rc, out = await _run_command(["bibtex", slug], out_dir)
        logs.append(out)
        if rc != 0:
            success = False
    if success:
        rc, out = await _run_command(
            ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_filename],
            out_dir,
        )
        logs.append(out)
        if rc != 0:
            success = False
    if success:
        rc, out = await _run_command(
            ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", tex_filename],
            out_dir,
        )
        logs.append(out)
        if rc != 0:
            success = False

    pdf_path = out_dir / f"{slug}.pdf"
    if not pdf_path.exists():
        success = False

    return {
        "compile_success": success,
        "pdf_path": str(pdf_path) if pdf_path.exists() else "",
        "compile_log": ("\n".join(notes) + "\n\n" + "\n\n".join(logs))[-20000:],
        "tex_path": str(tex_path),
        "bib_path": str(bib_path) if bib_path.exists() else "",
        "autofilled_bib_keys": missing_keys,
    }


async def _package_submission(
    title: str,
    tex_path: str,
    bib_path: str,
    pdf_path: str = "",
    compile_log_path: str = "",
    output_dir: str = "output",
    **kwargs: Any,
) -> dict[str, Any]:
    out_dir = Path(output_dir)
    out_dir.mkdir(exist_ok=True, parents=True)
    slug = _slugify(title)
    bundle = out_dir / f"{slug}-submission.zip"
    manifest = {
        "title": title,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "files": [],
    }
    files = [tex_path, bib_path, pdf_path, compile_log_path]
    with zipfile.ZipFile(bundle, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for fp in files:
            if not fp:
                continue
            p = Path(fp)
            if not p.exists():
                continue
            zf.write(p, arcname=p.name)
            manifest["files"].append(p.name)
        manifest_path = out_dir / f"{slug}.manifest.json"
        manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
        zf.write(manifest_path, arcname=manifest_path.name)
    return {"bundle_path": str(bundle), "saved_path": str(bundle), "title": title}


def _build_tool_registry() -> ToolRegistry:
    registry = ToolRegistry()
    builtin = registry.register_builtin_tools()
    logger.info("Registered %d built-in tools: %s", len(builtin), builtin)
    # Domain-specific tools override built-ins if they share an ID
    registry.register("save_paper", _save_paper)
    registry.register("search_papers", _search_papers)
    registry.register("citation_verifier", _citation_verifier)
    registry.register("check_latex_deps", _check_latex_deps)
    registry.register("compile_latex", _compile_latex)
    registry.register("package_submission", _package_submission)
    return registry


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _run_manager
    _run_manager = RunManager(
        engine_config=_get_engine_config(),
        tool_registry=_build_tool_registry(),
    )
    yield


app = FastAPI(title="Deep Agent Network", version="0.1.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ------------------------------------------------------------------
# Request / response schemas
# ------------------------------------------------------------------


class CreateGraphRequest(BaseModel):
    graph_id: str
    data: dict[str, Any] | None = None


class RunRequest(BaseModel):
    graph_id: str
    inputs: dict[str, Any] | None = None
    run_id: str | None = None


class ResumeRequest(BaseModel):
    graph_id: str


# ------------------------------------------------------------------
# Graph CRUD
# ------------------------------------------------------------------


@app.get("/api/graphs")
async def list_graphs():
    graphs = _graph_store.list_graphs()
    last_opened = _graph_store.get_last_opened()
    return {"graphs": graphs, "last_opened": last_opened}


@app.post("/api/graphs")
async def create_graph(req: CreateGraphRequest):
    if _graph_store.get_graph(req.graph_id) is not None:
        raise HTTPException(status_code=409, detail=f"Graph '{req.graph_id}' already exists")
    data = _graph_store.create_graph(req.graph_id, req.data)
    return {"graph_id": req.graph_id, "data": data}


_gate_migration_enabled = os.environ.get("DAN_GATE_MIGRATION_ENABLED", "").lower() in (
    "1", "true", "yes",
)


@app.get("/api/graphs/{graph_id}")
async def get_graph(graph_id: str):
    data = _graph_store.get_graph(graph_id)
    if data is None:
        raise HTTPException(status_code=404, detail=f"Graph '{graph_id}' not found")
    if _gate_migration_enabled and isinstance(data, dict):
        from dan.migration.gate_migration import migrate_graph
        data = migrate_graph(data)
    _graph_store.set_last_opened(graph_id)
    return {"graph_id": graph_id, "data": data}


@app.put("/api/graphs/{graph_id}")
async def update_graph(graph_id: str, body: dict[str, Any]):
    _graph_store.save_graph(graph_id, body)
    return {"graph_id": graph_id, "status": "saved"}


@app.delete("/api/graphs/{graph_id}")
async def delete_graph(graph_id: str):
    if not _graph_store.delete_graph(graph_id):
        raise HTTPException(status_code=404, detail=f"Graph '{graph_id}' not found")
    return {"graph_id": graph_id, "status": "deleted"}


@app.post("/api/graphs/{graph_id}/validate")
async def validate_graph_endpoint(graph_id: str):
    data = _graph_store.get_graph(graph_id)
    if data is None:
        raise HTTPException(status_code=404, detail=f"Graph '{graph_id}' not found")
    try:
        graph = Graph.model_validate(data)
    except Exception as exc:
        return {"errors": [{"message": f"Graph parse error: {exc}"}], "warnings": []}

    raw_errors = validate_graph(graph)
    errors: list[dict[str, str]] = []
    warnings: list[dict[str, str]] = []
    for msg in raw_errors:
        entry: dict[str, str] = {"message": msg}
        edge_match = re.search(r"(?:Edge|ContextEdge) '([^']+)'", msg)
        node_match = re.search(r"Node '([^']+)'", msg)
        cycle_match = re.search(r"non-loop node '([^']+)'", msg)
        if edge_match:
            entry["edge_id"] = edge_match.group(1)
        elif node_match:
            entry["node_id"] = node_match.group(1)
        elif cycle_match:
            entry["node_id"] = cycle_match.group(1)
        lower = msg.lower()
        is_warning = any(
            p in lower
            for p in ("schema safety bypassed", "untyped data edge", "deprecated")
        )
        if is_warning:
            warnings.append(entry)
        else:
            errors.append(entry)

    return {"errors": errors, "warnings": warnings}


@app.get("/api/graphs/{graph_id}/export/markdown")
async def export_graph_markdown(graph_id: str):
    graph = _graph_store.load_as_model(graph_id)
    if graph is None:
        raise HTTPException(status_code=404, detail=f"Graph '{graph_id}' not found")
    with tempfile.TemporaryDirectory() as tmpdir:
        result = decompile_to_markdown(graph, tmpdir)
        files: list[dict[str, str]] = []
        for p in result.files:
            content = p.read_text(encoding="utf-8")
            files.append({"path": p.name, "content": content})
        diagnostics: list[dict[str, Any]] = [
            {
                "level": d.level,
                "message": d.message,
                "source_file": str(d.source_file) if d.source_file else None,
                "source_line": d.source_line,
                "source_column": d.source_column,
                "hint": d.hint,
            }
            for d in result.diagnostics
        ]
        return {"files": files, "diagnostics": diagnostics}


@app.get("/api/graphs/{graph_id}/export/python")
async def export_graph_python(graph_id: str):
    graph = _graph_store.load_as_model(graph_id)
    if graph is None:
        raise HTTPException(status_code=404, detail=f"Graph '{graph_id}' not found")
    code = decompile_to_python(graph)
    return {"code": code}


# ------------------------------------------------------------------
# Run management
# ------------------------------------------------------------------


@app.post("/api/runs")
async def start_run(req: RunRequest):
    rm = _require_run_manager()
    graph = _graph_store.load_as_model(req.graph_id)
    if graph is None:
        raise HTTPException(status_code=404, detail=f"Graph '{req.graph_id}' not found")
    record = await rm.start_run(
        graph, graph_id=req.graph_id, inputs=req.inputs, run_id=req.run_id,
    )
    return {"run_id": record.run_id, "status": record.status.value}


@app.post("/api/runs/{run_id}/resume")
async def resume_run(run_id: str, req: ResumeRequest):
    rm = _require_run_manager()
    graph = _graph_store.load_as_model(req.graph_id)
    if graph is None:
        raise HTTPException(status_code=404, detail=f"Graph '{req.graph_id}' not found")
    record = await rm.resume_run(graph, graph_id=req.graph_id, run_id=run_id)
    return {"run_id": record.run_id, "status": record.status.value}


@app.get("/api/runs/{run_id}")
async def get_run(run_id: str):
    rm = _require_run_manager()
    record = rm.get_run(run_id)
    if record is None:
        raise HTTPException(status_code=404, detail=f"Run '{run_id}' not found")
    return record.snapshot()


@app.get("/api/runs")
async def list_runs():
    rm = _require_run_manager()
    return {"runs": rm.list_runs()}


@app.post("/api/runs/{run_id}/human-input")
async def submit_human_input(run_id: str, body: dict):
    rm = _require_run_manager()
    request_id = body.get("request_id")
    response = body.get("response", {})
    if not request_id:
        raise HTTPException(400, "request_id is required")
    record = rm.get_run(run_id)
    if record is None:
        raise HTTPException(404, f"Run '{run_id}' not found")
    if isinstance(response, str):
        response = {"response": response}
    ok = rm.submit_human_input(run_id, request_id, response)
    if not ok:
        raise HTTPException(404, f"No pending human-input request '{request_id}'")
    return {"status": "submitted", "request_id": request_id}


# ------------------------------------------------------------------
# WebSocket — live run events
# ------------------------------------------------------------------


@app.websocket("/api/runs/{run_id}/events")
async def run_events_ws(websocket: WebSocket, run_id: str):
    rm = _require_run_manager()
    await websocket.accept()

    queue = rm.subscribe(run_id)
    try:
        while True:
            event = await queue.get()
            await websocket.send_json(event)
    except WebSocketDisconnect:
        pass
    except Exception:
        logger.debug("WebSocket error for run %s", run_id, exc_info=True)
    finally:
        rm.unsubscribe(run_id, queue)


# ------------------------------------------------------------------
# Static file serving for the built editor (production)
# ------------------------------------------------------------------

_editor_dist = os.path.join(os.path.dirname(__file__), "..", "..", "..", "editor", "dist")
if os.path.isdir(_editor_dist):
    app.mount("/", StaticFiles(directory=_editor_dist, html=True), name="editor")
