#!/usr/bin/env python3
"""Run the multi-department adaptive workflow (v2 — state_schema).

Usage:
    python examples/vibe_research_v2_md/run_multi_dept.py
    python examples/vibe_research_v2_md/run_multi_dept.py --start 2012 --end 2022
    python examples/vibe_research_v2_md/run_multi_dept.py --max-factors 10
    python examples/vibe_research_v2_md/run_multi_dept.py --build-only
    python examples/vibe_research_v2_md/run_multi_dept.py --emit-python
    python examples/vibe_research_v2_md/run_multi_dept.py --from-json graphs/vibe_research_v2_multi_dept.json
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

from dan.builder.decompiler import decompile
from dan.loader import compile_workflow
from dan.engine import Engine, EngineConfig
from dan.engine.executor import ExecutorRegistry
from dan.engine.events import EventType, EngineEvent
from dan.executors.tool import ToolExecutor, ToolRegistry


def _build_tool_registry() -> ToolRegistry:
    """Build registry with required backtest and strategy tools."""
    project_root = Path(__file__).resolve().parents[2]
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))
    from dan.server.tools.quant import (
        _run_backtest,
        _run_strategy_script,
    )

    reg = ToolRegistry()
    reg.register_builtin_tools()
    reg.register("run_backtest", _run_backtest)
    reg.register("run_strategy_script", _run_strategy_script)
    return reg


def main() -> None:
    parser = argparse.ArgumentParser(description="Multi-department adaptive workflow (v2)")
    parser.add_argument("--start", type=int, default=2010)
    parser.add_argument("--end", type=int, default=2023)
    parser.add_argument("--max-factors", type=int, default=20, help="Hard limit: stop when this many factors generated")
    parser.add_argument("--build-only", action="store_true")
    parser.add_argument("--emit-python", action="store_true", help="Write twin Python builder script")
    parser.add_argument("--from-json", type=str, default="", help="Load pre-compiled graph JSON")
    parser.add_argument("--debug-events", action="store_true", help="Print gate/iteration events to stderr")
    args = parser.parse_args()

    workflow_dir = Path(__file__).parent

    if args.from_json:
        from dan.models.graph import Graph
        json_path = Path(args.from_json)
        if not json_path.exists():
            print(f"Graph JSON not found: {json_path}")
            raise SystemExit(1)
        graph = Graph.model_validate_json(json_path.read_text(encoding="utf-8"))

        class _Result:
            pass
        result = _Result()
        result.graph = graph
        result.diagnostics = []
        print(f"Loaded graph from {json_path}: {len(graph.nodes)} nodes, {len(graph.edges)} edges")
    else:
        result = compile_workflow(workflow_dir / "workflow_multi_dept.md")
        if not result.graph:
            for d in result.diagnostics:
                print(f"{d.severity}: {d.message}")
            raise SystemExit(1)

    if args.emit_python:
        code = decompile(result.graph)
        out_path = workflow_dir / "workflow_multi_dept_builder.py"
        header = '"""Twin Python builder for workflow_multi_dept.md (v2) — same graph via dan.builder DSL.\n\nGenerated by: python run_multi_dept.py --emit-python\n"""\n'
        out_path.write_text(header + code, encoding="utf-8")
        print(f"Saved {out_path}")
        return

    if args.build_only:
        graphs_dir = Path("graphs")
        graphs_dir.mkdir(exist_ok=True)
        data = result.graph.model_dump(mode="json")
        path = graphs_dir / "vibe_research_v2_multi_dept.json"
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        print(f"Saved {path}")
        return

    config = EngineConfig(
        llm_api_key=os.environ.get("DAN_LLM_API_KEY", ""),
        llm_base_url=os.environ.get("DAN_LLM_BASE_URL", "https://api.vectorengine.ai/v1"),
        llm_default_model=os.environ.get("DAN_LLM_MODEL", "claude-sonnet-4-6"),
    )
    tool_registry = _build_tool_registry()
    exec_registry = ExecutorRegistry()
    exec_registry.register("tool_operator", ToolExecutor(tool_registry))

    async def _debug_event_callback(ev: EngineEvent) -> None:
        if ev.event_type == EventType.GATE_EVALUATED:
            print(f"[gate_evaluated] {ev.data}", file=sys.stderr)
        elif ev.event_type in (EventType.ITERATION_STARTED, EventType.ITERATION_COMPLETED):
            print(f"[{ev.event_type.value}] {ev.data}", file=sys.stderr)
        elif ev.event_type == EventType.NODE_COMPLETED:
            print(f"[node_completed] {ev.node_id}", file=sys.stderr)

    event_cb = _debug_event_callback if args.debug_events else None
    engine = Engine(config, executor_registry=exec_registry, event_callback=event_cb)

    async def run() -> None:
        run_result = await engine.run(
            result.graph,
            inputs={"start_year": args.start, "end_year": args.end, "max_factors": args.max_factors},
        )
        print("Success:", run_result.success)
        if run_result.outputs:
            for k, v in run_result.outputs.items():
                print(f"  {k}:", v)
        if run_result.errors:
            print("Errors:", run_result.errors)

    asyncio.run(run())


if __name__ == "__main__":
    main()
